# Generated by Django 5.2.7 on 2025-11-11 00:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdministrativeUnit",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "administrative_unit_id",
                    models.AutoField(
                        db_column="AdministrativeUnitID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_name", models.CharField(db_column="UnitName", max_length=255)),
                (
                    "unit_abbreviation",
                    models.CharField(db_column="UnitAbbreviation", max_length=10),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("COUNTRY", "Country"),
                            ("STATE", "State"),
                            ("PROVINCE", "Province"),
                            ("TERRITORY", "Territory"),
                            ("PREFECTURE", "Prefecture"),
                            ("COUNTY", "County"),
                        ],
                        db_column="UnitType",
                        max_length=20,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        db_column="HierarchyLevel",
                        help_text="1=Country, 2=State/Province, 3=County, etc",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_administrative_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="ParentAdministrativeUnitID",
                        help_text="Self-referencing for hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_units",
                        to="common.administrativeunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit",
                "verbose_name_plural": "Administrative Units",
                "db_table": "AdministrativeUnits",
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnitHistory",
            fields=[
                (
                    "administrative_unit_history_id",
                    models.AutoField(
                        db_column="AdministrativeUnitHistoryID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unit_name", models.CharField(db_column="UnitName", max_length=255)),
                (
                    "unit_abbreviation",
                    models.CharField(db_column="UnitAbbreviation", max_length=10),
                ),
                ("unit_type", models.CharField(db_column="UnitType", max_length=20)),
                ("hierarchy_level", models.IntegerField(db_column="HierarchyLevel")),
                (
                    "is_active",
                    models.BooleanField(
                        db_column="IsActive",
                        help_text="Was this unit active during this period?",
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateField(db_column="EffectiveFromDate"),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True,
                        db_column="EffectiveToDate",
                        help_text="NULL if current version",
                        null=True,
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("SPLIT", "Split"),
                            ("MERGED", "Merged"),
                            ("RENAMED", "Renamed"),
                            ("INDEPENDENCE", "Independence"),
                            ("ANNEXED", "Annexed"),
                            ("REORGANIZED", "Reorganized"),
                        ],
                        db_column="ChangeReason",
                        max_length=20,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrative_unit_history_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_administrative_unit",
                    models.ForeignKey(
                        blank=True,
                        db_column="ParentAdministrativeUnitID",
                        help_text="Which unit this belonged to at this time",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_children",
                        to="common.administrativeunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit History",
                "verbose_name_plural": "Administrative Unit Histories",
                "db_table": "AdministrativeUnitHistory",
                "ordering": ["-effective_from_date"],
            },
        ),
        migrations.CreateModel(
            name="AdministrativeUnitNameHistory",
            fields=[
                (
                    "administrative_unit_name_history_id",
                    models.AutoField(
                        db_column="AdministrativeUnitNameHistoryID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "historical_name",
                    models.CharField(db_column="HistoricalName", max_length=255),
                ),
                (
                    "historical_abbreviation",
                    models.CharField(db_column="HistoricalAbbreviation", max_length=10),
                ),
                (
                    "effective_from_date",
                    models.DateField(db_column="EffectiveFromDate"),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True, db_column="EffectiveToDate", null=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_history",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrative_unit_name_history_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Unit Name History",
                "verbose_name_plural": "Administrative Unit Name Histories",
                "db_table": "AdministrativeUnitNameHistory",
                "ordering": ["-effective_from_date"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "color_id",
                    models.AutoField(
                        db_column="ColorID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "color_name",
                    models.CharField(db_column="ColorName", max_length=50, unique=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
                "db_table": "Colors",
                "ordering": ["color_name"],
            },
        ),
        migrations.CreateModel(
            name="DateFormat",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "date_format_id",
                    models.AutoField(
                        db_column="DateFormatID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "format_name",
                    models.CharField(
                        db_column="FormatName", max_length=100, unique=True
                    ),
                ),
                (
                    "format_description",
                    models.TextField(blank=True, db_column="FormatDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Date Format",
                "verbose_name_plural": "Date Formats",
                "db_table": "DateFormats",
                "ordering": ["format_name"],
            },
        ),
        migrations.CreateModel(
            name="FramingStyle",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "framing_style_id",
                    models.AutoField(
                        db_column="FramingStyleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "framing_style_name",
                    models.CharField(
                        db_column="FramingStyleName", max_length=100, unique=True
                    ),
                ),
                (
                    "framing_description",
                    models.TextField(blank=True, db_column="FramingDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Framing Style",
                "verbose_name_plural": "Framing Styles",
                "db_table": "FramingStyles",
                "ordering": ["framing_style_name"],
            },
        ),
        migrations.CreateModel(
            name="GeographicLocation",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "geographic_location_id",
                    models.AutoField(
                        db_column="GeographicLocationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_name",
                    models.CharField(db_column="LocationName", max_length=255),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("TOWN", "Town"),
                            ("CITY", "City"),
                            ("VILLAGE", "Village"),
                            ("POST_OFFICE", "Post Office"),
                            ("SETTLEMENT", "Settlement"),
                        ],
                        db_column="LocationType",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Latitude",
                        decimal_places=7,
                        help_text="Nullable - for towns/cities, optional for regions",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_column="Longitude",
                        decimal_places=7,
                        help_text="Nullable - for towns/cities, optional for regions",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic Location",
                "verbose_name_plural": "Geographic Locations",
                "db_table": "GeographicLocations",
            },
        ),
        migrations.CreateModel(
            name="GeographicAffiliation",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "geographic_affiliation_id",
                    models.AutoField(
                        db_column="GeographicAffiliationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "effective_from_date",
                    models.DateField(
                        db_column="EffectiveFromDate",
                        help_text="When this affiliation began",
                    ),
                ),
                (
                    "effective_to_date",
                    models.DateField(
                        blank=True,
                        db_column="EffectiveToDate",
                        help_text="When ended, NULL if current",
                        null=True,
                    ),
                ),
                (
                    "affiliation_source",
                    models.CharField(
                        db_column="AffiliationSource",
                        help_text="Treaty, Act, Historical Record, etc",
                        max_length=255,
                    ),
                ),
                (
                    "administrative_unit",
                    models.ForeignKey(
                        db_column="AdministrativeUnitID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governed_locations",
                        to="common.administrativeunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geographic_location",
                    models.ForeignKey(
                        db_column="GeographicLocationID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="common.geographiclocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geographic Affiliation",
                "verbose_name_plural": "Geographic Affiliations",
                "db_table": "GeographicAffiliations",
            },
        ),
        migrations.CreateModel(
            name="LetteringStyle",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "lettering_style_id",
                    models.AutoField(
                        db_column="LetteringStyleID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "lettering_style_name",
                    models.CharField(
                        db_column="LetteringStyleName", max_length=100, unique=True
                    ),
                ),
                (
                    "lettering_description",
                    models.TextField(blank=True, db_column="LetteringDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettering Style",
                "verbose_name_plural": "Lettering Styles",
                "db_table": "LetteringStyles",
                "ordering": ["lettering_style_name"],
            },
        ),
        migrations.CreateModel(
            name="Postcover",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postcover_id",
                    models.AutoField(
                        db_column="PostcoverID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "postcover_key",
                    models.CharField(
                        db_column="PostcoverKey", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, db_column="Description")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        db_column="OwnerUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postcovers_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover",
                "verbose_name_plural": "Postcovers",
                "db_table": "Postcovers",
            },
        ),
        migrations.CreateModel(
            name="PostcoverImage",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postcover_image_id",
                    models.AutoField(
                        db_column="PostcoverImageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(db_column="OriginalFileName", max_length=255),
                ),
                (
                    "storage_filename",
                    models.CharField(
                        db_column="StorageFileName", max_length=255, unique=True
                    ),
                ),
                (
                    "file_checksum",
                    models.CharField(
                        db_column="FileChecksum",
                        help_text="SHA-256 or MD5 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        db_column="MimeType",
                        help_text="image/jpeg, image/png, image/tiff, etc",
                        max_length=50,
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(
                        db_column="ImageWidth", help_text="Width in pixels"
                    ),
                ),
                (
                    "image_height",
                    models.IntegerField(
                        db_column="ImageHeight", help_text="Height in pixels"
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(db_column="FileSizeBytes")),
                (
                    "image_view",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front"),
                            ("BACK", "Back"),
                            ("INTERIOR", "Interior"),
                            ("DETAIL", "Detail"),
                        ],
                        db_column="ImageView",
                        max_length=20,
                    ),
                ),
                (
                    "image_description",
                    models.TextField(blank=True, db_column="ImageDescription"),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        db_column="DisplayOrder",
                        default=0,
                        help_text="0 = main image, 1+ = additional images",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postcover",
                    models.ForeignKey(
                        db_column="PostcoverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="common.postcover",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        db_column="UploadedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postcover_images_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover Image",
                "verbose_name_plural": "Postcover Images",
                "db_table": "PostcoverImages",
                "ordering": ["postcover", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="Postmark",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postmark_id",
                    models.AutoField(
                        db_column="PostmarkID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "postmark_key",
                    models.CharField(
                        db_column="PostmarkKey", max_length=100, unique=True
                    ),
                ),
                (
                    "rate_location",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("BOTTOM", "Bottom"),
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("CENTER", "Center"),
                            ("NONE", "None"),
                        ],
                        db_column="RateLocation",
                        help_text="Top/Bottom/Left/Right/Center/None",
                        max_length=10,
                    ),
                ),
                (
                    "rate_value",
                    models.CharField(
                        db_column="RateValue",
                        help_text="5c, 10c, Free, Paid, etc",
                        max_length=50,
                    ),
                ),
                (
                    "is_manuscript",
                    models.BooleanField(
                        db_column="IsManuscript",
                        default=False,
                        help_text="Hand-written or hand-stamped vs printed",
                    ),
                ),
                (
                    "other_characteristics",
                    models.TextField(blank=True, db_column="OtherCharacteristics"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "date_format",
                    models.ForeignKey(
                        db_column="DateFormatID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.dateformat",
                    ),
                ),
                (
                    "framing_style",
                    models.ForeignKey(
                        db_column="FramingStyleID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.framingstyle",
                    ),
                ),
                (
                    "geographic_location",
                    models.ForeignKey(
                        db_column="GeographicLocationID",
                        help_text="The physical location where postmark was used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.geographiclocation",
                    ),
                ),
                (
                    "lettering_style",
                    models.ForeignKey(
                        db_column="LetteringStyleID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmarks",
                        to="common.letteringstyle",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark",
                "verbose_name_plural": "Postmarks",
                "db_table": "Postmarks",
            },
        ),
        migrations.CreateModel(
            name="PostcoverPostmark",
            fields=[
                (
                    "postcover_postmark_id",
                    models.AutoField(
                        db_column="PostcoverPostmarkID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position_order",
                    models.IntegerField(
                        db_column="PositionOrder",
                        help_text="Order of postmarks on cover (1st, 2nd, etc)",
                    ),
                ),
                (
                    "postmark_location",
                    models.CharField(
                        choices=[
                            ("FRONT", "Front"),
                            ("BACK", "Back"),
                            ("FRONT_UPPER_RIGHT", "Front Upper Right"),
                            ("FRONT_UPPER_LEFT", "Front Upper Left"),
                            ("BACK_UPPER_RIGHT", "Back Upper Right"),
                            ("BACK_UPPER_LEFT", "Back Upper Left"),
                            ("BACK_LOWER_LEFT", "Back Lower Left"),
                            ("BACK_LOWER_RIGHT", "Back Lower Right"),
                        ],
                        db_column="PostmarkLocation",
                        max_length=20,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postcover_postmarks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postcover",
                    models.ForeignKey(
                        db_column="PostcoverID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postcover_postmarks",
                        to="common.postcover",
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postcover_postmarks",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postcover Postmark",
                "verbose_name_plural": "Postcover Postmarks",
                "db_table": "PostcoverPostmarks",
                "ordering": ["postcover", "position_order"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkColor",
            fields=[
                (
                    "postmark_color_id",
                    models.AutoField(
                        db_column="PostmarkColorID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "color",
                    models.ForeignKey(
                        db_column="ColorID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_colors",
                        to="common.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_colors_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmark_colors",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Color",
                "verbose_name_plural": "Postmark Colors",
                "db_table": "PostmarkColors",
            },
        ),
        migrations.CreateModel(
            name="PostmarkDatesSeen",
            fields=[
                (
                    "postmark_dates_seen_id",
                    models.AutoField(
                        db_column="PostmarkDatesSeenID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("earliest_date_seen", models.DateField(db_column="EarliestDateSeen")),
                ("latest_date_seen", models.DateField(db_column="LatestDateSeen")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_dates_seen_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates_seen",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Dates Seen",
                "verbose_name_plural": "Postmark Dates Seen",
                "db_table": "PostmarkDatesSeen",
                "ordering": ["earliest_date_seen"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkImage",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postmark_image_id",
                    models.AutoField(
                        db_column="PostmarkImageID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(db_column="OriginalFileName", max_length=255),
                ),
                (
                    "storage_filename",
                    models.CharField(
                        db_column="StorageFileName", max_length=255, unique=True
                    ),
                ),
                (
                    "file_checksum",
                    models.CharField(
                        db_column="FileChecksum",
                        help_text="SHA-256 or MD5 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        db_column="MimeType",
                        help_text="image/jpeg, image/png, image/tiff, etc",
                        max_length=50,
                    ),
                ),
                (
                    "image_width",
                    models.IntegerField(
                        db_column="ImageWidth", help_text="Width in pixels"
                    ),
                ),
                (
                    "image_height",
                    models.IntegerField(
                        db_column="ImageHeight", help_text="Height in pixels"
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(db_column="FileSizeBytes")),
                (
                    "image_view",
                    models.CharField(
                        choices=[
                            ("FULL", "Full"),
                            ("DETAIL", "Detail"),
                            ("COMPARISON", "Comparison"),
                        ],
                        db_column="ImageView",
                        max_length=20,
                    ),
                ),
                (
                    "image_description",
                    models.TextField(blank=True, db_column="ImageDescription"),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        db_column="DisplayOrder",
                        default=0,
                        help_text="0 = main image, 1+ = additional images",
                    ),
                ),
                (
                    "image_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_column="ImageStatus",
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        blank=True, db_column="SubmitterName", max_length=255
                    ),
                ),
                (
                    "submitter_email",
                    models.EmailField(
                        blank=True, db_column="SubmitterEmail", max_length=254
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Image",
                "verbose_name_plural": "Postmark Images",
                "db_table": "PostmarkImages",
                "ordering": ["postmark", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkPublication",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postmark_publication_id",
                    models.AutoField(
                        db_column="PostmarkPublicationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "publication_title",
                    models.CharField(db_column="PublicationTitle", max_length=500),
                ),
                ("author", models.CharField(db_column="Author", max_length=255)),
                ("publisher", models.CharField(db_column="Publisher", max_length=255)),
                ("publication_date", models.DateField(db_column="PublicationDate")),
                ("isbn", models.CharField(blank=True, db_column="ISBN", max_length=20)),
                (
                    "edition",
                    models.CharField(blank=True, db_column="Edition", max_length=50),
                ),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book"),
                            ("CATALOG", "Catalog"),
                            ("JOURNAL", "Journal"),
                            ("WEBSITE", "Website"),
                            ("NEWSLETTER", "Newsletter"),
                        ],
                        db_column="PublicationType",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Publication",
                "verbose_name_plural": "Postmark Publications",
                "db_table": "PostmarkPublications",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="PostmarkPublicationReference",
            fields=[
                (
                    "postmark_publication_reference_id",
                    models.AutoField(
                        db_column="PostmarkPublicationReferenceID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "published_id",
                    models.CharField(
                        db_column="PublishedID",
                        help_text="Reference ID/number in the publication",
                        max_length=100,
                    ),
                ),
                (
                    "reference_location",
                    models.CharField(
                        db_column="ReferenceLocation",
                        help_text="Page number (p. 45) or URL for websites",
                        max_length=255,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_publication_references_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_references",
                        to="common.postmark",
                    ),
                ),
                (
                    "postmark_publication",
                    models.ForeignKey(
                        db_column="PostmarkPublicationID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postmark_references",
                        to="common.postmarkpublication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Publication Reference",
                "verbose_name_plural": "Postmark Publication References",
                "db_table": "PostmarkPublicationReferences",
            },
        ),
        migrations.CreateModel(
            name="PostmarkShape",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postmark_shape_id",
                    models.AutoField(
                        db_column="PostmarkShapeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "shape_name",
                    models.CharField(
                        db_column="ShapeName", max_length=100, unique=True
                    ),
                ),
                (
                    "shape_description",
                    models.TextField(blank=True, db_column="ShapeDescription"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Shape",
                "verbose_name_plural": "Postmark Shapes",
                "db_table": "PostmarkShapes",
                "ordering": ["shape_name"],
            },
        ),
        migrations.AddField(
            model_name="postmark",
            name="postmark_shape",
            field=models.ForeignKey(
                db_column="PostmarkShapeID",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="postmarks",
                to="common.postmarkshape",
            ),
        ),
        migrations.CreateModel(
            name="PostmarkSize",
            fields=[
                (
                    "postmark_size_id",
                    models.AutoField(
                        db_column="PostmarkSizeID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        db_column="Width", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        db_column="Height", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "size_notes",
                    models.CharField(
                        blank=True,
                        db_column="SizeNotes",
                        help_text="e.g., Blown up, Scaled, Standard",
                        max_length=255,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedDate"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_sizes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="common.postmark",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Size",
                "verbose_name_plural": "Postmark Sizes",
                "db_table": "PostmarkSizes",
            },
        ),
        migrations.CreateModel(
            name="PostmarkValuation",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "postmark_valuation_id",
                    models.AutoField(
                        db_column="PostmarkValuationID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        db_column="EstimatedValue", decimal_places=2, max_digits=10
                    ),
                ),
                ("valuation_date", models.DateField(db_column="ValuationDate")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="CreatedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="ModifiedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postmark",
                    models.ForeignKey(
                        db_column="PostmarkID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuations",
                        to="common.postmark",
                    ),
                ),
                (
                    "valued_by_user",
                    models.ForeignKey(
                        db_column="ValuedByUserID",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="postmark_valuations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Postmark Valuation",
                "verbose_name_plural": "Postmark Valuations",
                "db_table": "PostmarkValuations",
                "ordering": ["-valuation_date"],
            },
        ),
        migrations.AddIndex(
            model_name="administrativeunit",
            index=models.Index(
                fields=["unit_type", "hierarchy_level"],
                name="Administrat_UnitTyp_df1739_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="administrativeunit",
            index=models.Index(
                fields=["unit_abbreviation"], name="Administrat_UnitAbb_cd010b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geographiclocation",
            index=models.Index(
                fields=["location_name", "location_type"],
                name="GeographicL_Locatio_07cca9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geographicaffiliation",
            index=models.Index(
                fields=["geographic_location", "effective_from_date"],
                name="GeographicA_Geograp_afc4a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="geographicaffiliation",
            index=models.Index(
                fields=["administrative_unit", "effective_from_date"],
                name="GeographicA_Adminis_759931_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postcover",
            index=models.Index(
                fields=["owner_user"], name="Postcovers_OwnerUs_3a89ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcover",
            index=models.Index(
                fields=["postcover_key"], name="Postcovers_Postcov_a79a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcoverimage",
            index=models.Index(
                fields=["postcover", "display_order"],
                name="PostcoverIm_Postcov_cb9bda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postcoverimage",
            index=models.Index(
                fields=["file_checksum"], name="PostcoverIm_FileChe_1473bb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postcoverpostmark",
            unique_together={("postcover", "postmark", "position_order")},
        ),
        migrations.AlterUniqueTogether(
            name="postmarkcolor",
            unique_together={("postmark", "color")},
        ),
        migrations.AddIndex(
            model_name="postmarkimage",
            index=models.Index(
                fields=["postmark", "display_order"],
                name="PostmarkIma_Postmar_a95f9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postmarkimage",
            index=models.Index(
                fields=["file_checksum"], name="PostmarkIma_FileChe_1d7426_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="postmarkpublicationreference",
            unique_together={("postmark", "postmark_publication", "published_id")},
        ),
        migrations.AddIndex(
            model_name="postmark",
            index=models.Index(
                fields=["geographic_location"], name="Postmarks_Geograp_2be893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postmark",
            index=models.Index(
                fields=["postmark_key"], name="Postmarks_Postmar_c85d2f_idx"
            ),
        ),
    ]
