# Generated by Django 5.2.7 on 2025-11-16 17:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="color_value",
            field=colorfield.fields.ColorField(
                db_column="ColorValue",
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
