# Generated by Django 5.2.7 on 2026-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_state_fk_to_location_proxy'),
        ('postmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.administrativeunit',),
        ),
        migrations.CreateModel(
            name='LocationIdentity',
            fields=[
            ],
            options={
                'verbose_name': 'Location identity',
                'verbose_name_plural': 'Location identities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.administrativeunitidentity',),
        ),
        migrations.CreateModel(
            name='LocationResponsibility',
            fields=[
            ],
            options={
                'verbose_name': 'Location responsibility',
                'verbose_name_plural': 'Location responsibilities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.administrativeunitresponsibility',),
        ),
    ]
