# Generated by Django 5.2.7 on 2026-03-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmarks', '0002_state_fk_to_location_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Catalog request',
                'verbose_name_plural': 'Catalog requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('postmarks.listing',),
        ),
    ]
