# Generated by Django 5.2.7 on 2026-04-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_remove_postmark_postmarks_postalf_b9397c_idx_and_more'),
        ('postmarks', '0004_remove_junk_proxies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.contribution',),
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.faqentry',),
        ),
        migrations.AlterModelOptions(
            name='postcover',
            options={'verbose_name': 'Example Cover (Deprecated)', 'verbose_name_plural': 'Example Covers (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='postcoverimage',
            options={'verbose_name': 'Example Image (Deprecated)', 'verbose_name_plural': 'Example Images (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='postcoverpostmark',
            options={'verbose_name': 'Example Cover Marking (Deprecated)', 'verbose_name_plural': 'Example Cover Markings (Deprecated)'},
        ),
    ]
