# Generated by Django 5.2.7 on 2026-04-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmarks', '0007_delete_location_proxies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogRequest',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='FAQEntry',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
        migrations.DeleteModel(
            name='Postcover',
        ),
        migrations.DeleteModel(
            name='PostcoverImage',
        ),
        migrations.DeleteModel(
            name='PostcoverPostmark',
        ),
        migrations.DeleteModel(
            name='PostmarkValuation',
        ),
    ]
