# Generated by OpenClaw on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmark',
            name='raw_state_data_id',
            field=models.IntegerField(
                blank=True,
                null=True,
                unique=True,
                db_column='RawStateDataID',
                help_text='Original nRawStateDataID from CSV import',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='public_slug',
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                max_length=150,
                db_column='PublicSlug',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='visibility',
            field=models.CharField(
                choices=[('PUBLIC', 'Public'), ('DRAFT', 'Draft'), ('ARCHIVED', 'Archived')],
                default='PUBLIC',
                max_length=10,
                db_column='Visibility',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='source_catalog',
            field=models.CharField(
                blank=True,
                default='ASCC 5th ed. (1997)',
                max_length=255,
                db_column='SourceCatalog',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='source_page',
            field=models.CharField(
                blank=True,
                max_length=50,
                db_column='SourcePage',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='last_public_update_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                db_column='LastPublicUpdateAt',
            ),
        ),
        migrations.AddField(
            model_name='postmark',
            name='raw_import_payload',
            field=models.JSONField(
                blank=True,
                null=True,
                db_column='RawImportPayload',
                help_text='Full raw CSV row payload for import/backfill',
            ),
        ),
    ]
