# Generated by OpenClaw on 2026-02-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_listing_admin_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmark',
            options={'db_table': 'Postmarks', 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='postmarkimage',
            options={'db_table': 'PostmarkImages', 'ordering': ['postmark', 'display_order'], 'verbose_name': 'Listing Image', 'verbose_name_plural': 'Listing Images'},
        ),
        migrations.AlterModelOptions(
            name='postcover',
            options={'db_table': 'Postcovers', 'verbose_name': 'Example Cover', 'verbose_name_plural': 'Example Covers'},
        ),
        migrations.AlterModelOptions(
            name='postcoverpostmark',
            options={'db_table': 'PostcoverPostmarks', 'ordering': ['postcover', 'position_order'], 'verbose_name': 'Example Cover Marking', 'verbose_name_plural': 'Example Cover Markings', 'unique_together': {('postcover', 'postmark', 'position_order')}},
        ),
        migrations.AlterModelOptions(
            name='postcoverimage',
            options={'db_table': 'PostcoverImages', 'ordering': ['postcover', 'display_order'], 'verbose_name': 'Example Image', 'verbose_name_plural': 'Example Images'},
        ),
    ]
