# Generated by OpenClaw on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_verbose_names'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmark',
            name='site',
            field=models.ForeignKey(default=1, db_column='SiteID', help_text='Owning site for this listing', on_delete=django.db.models.deletion.PROTECT, related_name='postmarks', to='sites.site'),
        ),
    ]
