# Generated by OpenClaw on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_postmark_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='postal_facility_identity',
            field=models.ForeignKey(blank=True, db_column='PostalFacilityIdentityID', help_text='The facility identity when this postmark was used', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks', to='common.postalfacilityidentity'),
        ),
    ]
