# Generated by Django (AdminCsvUpload.row_count for list API without loading Data)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_admin_csv_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincsvupload',
            name='row_count',
            field=models.PositiveIntegerField(db_column='RowCount', default=0, help_text='Number of data rows (denormalized for list views without loading Data).'),
        ),
    ]
