# Generated by Django 5.2.7 on 2026-02-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_legacy_erd_tables'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmark',
            options={'ordering': ['postmark_id'], 'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AddField(
            model_name='postmark',
            name='state',
            field=models.ForeignKey(blank=True, db_column='StateID', help_text='State (administrative unit) this listing belongs to; from import nStateID or facility jurisdiction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks_by_state', to='common.administrativeunit'),
        ),
        migrations.AddIndex(
            model_name='postmark',
            index=models.Index(fields=['state'], name='Postmarks_StateID_084a2a_idx'),
        ),
    ]
