# Generated by Django 5.2.7 on 2026-02-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_add_postmark_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeunit',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='administrativeunitidentity',
            options={'ordering': ['administrative_unit', '-effective_from_date'], 'verbose_name': 'Location identity', 'verbose_name_plural': 'Location identities'},
        ),
        migrations.AlterModelOptions(
            name='administrativeunitresponsibility',
            options={'verbose_name': 'Location responsibility', 'verbose_name_plural': 'Location responsibilities'},
        ),
    ]
