# Generated by Django 5.2.7 on 2026-02-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_state_fk_to_location_proxy'),
        ('postmarks', '0002_state_fk_to_location_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='state',
            field=models.ForeignKey(blank=True, db_column='StateID', help_text='Location (state/region) this listing belongs to; from import nStateID or facility jurisdiction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks_by_state', to='postmarks.location'),
        ),
    ]
