# Generated by Django 5.2.7 on 2026-02-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_state_fk_to_location_proxy'),
        ('postmarks', '0002_state_fk_to_location_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeunitidentity',
            name='administrative_unit',
            field=models.ForeignKey(db_column='AdministrativeUnitID', on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='postmarks.location'),
        ),
        migrations.AlterField(
            model_name='administrativeunitidentity',
            name='parent_administrative_unit',
            field=models.ForeignKey(blank=True, db_column='ParentAdministrativeUnitID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_identities', to='postmarks.location'),
        ),
        migrations.AlterField(
            model_name='administrativeunitresponsibility',
            name='administrative_unit',
            field=models.ForeignKey(db_column='AdministrativeUnitID', help_text='The location this group is responsible for', on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='postmarks.location'),
        ),
        migrations.AlterField(
            model_name='jurisdictionalaffiliation',
            name='administrative_unit',
            field=models.ForeignKey(db_column='AdministrativeUnitID', on_delete=django.db.models.deletion.PROTECT, related_name='governed_facilities', to='postmarks.location'),
        ),
    ]
