# Generated by Django 5.2.7 on 2026-03-05 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_postmark_created_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # We assume the `UserLocationAssignments` table already exists in the
            # database (from a previous partial migration run or manual creation),
            # so we only update Django's migration state to include the model and
            # its fields without issuing any CREATE TABLE statements.
            state_operations=[
                migrations.CreateModel(
                    name='UserLocationAssignment',
                    fields=[
                        (
                            'id',
                            models.AutoField(
                                primary_key=True,
                                db_column='UserLocationAssignmentID',
                                serialize=False,
                            ),
                        ),
                        (
                            'user',
                            models.ForeignKey(
                                db_column='UserID',
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='location_assignments',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'administrative_unit',
                            models.ForeignKey(
                                db_column='AdministrativeUnitID',
                                help_text='Location this user is associated with',
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='user_location_assignments',
                                to='common.administrativeunit',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'UserLocationAssignments',
                        'verbose_name': 'User location assignment',
                        'verbose_name_plural': 'User location assignments',
                        'unique_together': {('user', 'administrative_unit')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
