# Generated by Django 5.2.7 on 2026-03-03 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_postmark_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogContributionRequest',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate')),
                ('catalog_contribution_request_id', models.AutoField(db_column='CatalogContributionRequestID', primary_key=True, serialize=False)),
                ('submitter_name', models.CharField(db_column='SubmitterName', max_length=255)),
                ('submitter_email', models.EmailField(blank=True, db_column='SubmitterEmail', max_length=254)),
                ('state', models.CharField(db_column='State', max_length=255)),
                ('town', models.CharField(db_column='Town', max_length=255)),
                ('first_seen', models.CharField(db_column='FirstSeen', max_length=20)),
                ('last_seen', models.CharField(blank=True, db_column='LastSeen', max_length=20)),
                ('type', models.CharField(db_column='Type', max_length=255)),
                ('color', models.CharField(db_column='Color', max_length=255)),
                ('manuscript', models.CharField(blank=True, db_column='Manuscript', max_length=50)),
                ('dimensions', models.CharField(blank=True, db_column='Dimensions', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description')),
                ('references', models.TextField(blank=True, db_column='References')),
                ('rarity', models.CharField(blank=True, db_column='Rarity', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, db_column='RawPayload', default=dict, help_text='Original payload from contribute form, including any image metadata.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Needs revision')], db_column='Status', default='PENDING', max_length=20)),
                ('status_notes', models.TextField(blank=True, db_column='StatusNotes', help_text='Internal notes from admin about approval/rejection or requested changes.')),
            ],
            options={
                'verbose_name': 'Catalog Contribution Request',
                'verbose_name_plural': 'Catalog Contribution Requests',
                'db_table': 'CatalogContributionRequests',
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='postmark',
            name='Postmarks_Created_idx',
        ),
        migrations.RemoveIndex(
            model_name='postmark',
            name='Postmarks_Shape_idx',
        ),
        migrations.RemoveIndex(
            model_name='postmark',
            name='Postmarks_Manuscript_idx',
        ),
        migrations.AddField(
            model_name='catalogcontributionrequest',
            name='created_by',
            field=models.ForeignKey(db_column='CreatedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogcontributionrequest',
            name='modified_by',
            field=models.ForeignKey(db_column='ModifiedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogcontributionrequest',
            name='postmark',
            field=models.ForeignKey(blank=True, db_column='PostmarkID', help_text='Catalog listing created when this request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_requests', to='common.postmark'),
        ),
        migrations.AddIndex(
            model_name='catalogcontributionrequest',
            index=models.Index(fields=['status'], name='CatalogCont_Status_18177a_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcontributionrequest',
            index=models.Index(fields=['submitter_name'], name='CatalogCont_Submitt_1d6e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogcontributionrequest',
            index=models.Index(fields=['submitter_email'], name='CatalogCont_Submitt_6ad0f9_idx'),
        ),
    ]
