# Generated by Django 5.2.7 on 2026-03-03 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_catalogcontributionrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcontributionrequest',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_column='Action', default='CREATE', help_text='Type of request: create new listing, update existing, or delete existing.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='catalogcontributionrequest',
            index=models.Index(fields=['action'], name='CatalogCont_Action_4cd5f5_idx'),
        ),
    ]
