# Generated by Claude Code on 2026-09-23 (Trello T67, issues.md 172)
#
# Cover.type grew from FC/FL to six codes after Ian's 2026-09-23 "Cover
# Options" thread with the state editors: Folded Letter, Folded Letter Front,
# Envelope, Envelope Front, plus Unknown (Ian, in person). FC stays for the
# rows that already carry it. The longest code is four characters, so the
# column widens from 2 to 4; no row is rewritten.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_recompute_marking_date_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('FL', 'Folded Letter'),
                    ('FLF', 'Folded Letter Front'),
                    ('ENV', 'Envelope'),
                    ('ENVF', 'Envelope Front'),
                    ('FC', 'Folded Cover'),
                    ('UNK', 'Unknown'),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
