# Generated by Django 5.2.7 on 2026-03-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_userlocationassignment_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postmark',
            name='Postmarks_Created_idx',
        ),
    ]
