# Generated by Django 5.2.7 on 2026-03-05 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_catalogcontributionrequest_action_and_more'),
        ('postmarks', '0002_state_fk_to_location_proxy'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmark',
            name='moderation_notes',
            field=models.TextField(blank=True, db_column='ModerationNotes', help_text='Internal notes about why this listing is approved/rejected/needs revision.'),
        ),
        migrations.AddField(
            model_name='postmark',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Needs revision')], db_column='ModerationStatus', default='APPROVED', help_text='Editorial review state for this catalog entry.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='postmark',
            index=models.Index(fields=['moderation_status'], name='Postmarks_Moderat_3933c2_idx'),
        ),
    ]
