# Generated by Claude Code on 2026-09-24 (issues.md 107)
#
# Three SubmissionTransaction actions for one DateSeen row added, changed or
# removed through /dates-seen/. They were logged as record_create/update/
# delete, so a marking's changelog read "Record deleted by ..." when an editor
# removed a date. Choices only; no row is rewritten.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_cover_type_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontransaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("submit", "Record submitted"),
                    ("edit_submission", "Edited submission"),
                    ("editor_edit", "Editor edit"),
                    ("approve", "Approved"),
                    ("reject", "Rejected"),
                    ("catalog_direct_edit", "Catalog direct edit"),
                    ("restore_version", "Restored version"),
                    ("record_create", "Record created"),
                    ("record_update", "Record updated"),
                    ("record_delete", "Record deleted"),
                    ("draft_deleted", "Draft deleted"),
                    ("contribution_superseded", "Contribution superseded"),
                    ("marking_removed", "Marking removed"),
                    ("marking_restored", "Marking restored"),
                    ("cover_removed", "Cover removed"),
                    ("cover_restored", "Cover restored"),
                    ("contribution_archived", "Contribution archived"),
                    ("contribution_restored", "Contribution restored"),
                    ("date_seen_added", "Date added"),
                    ("date_seen_changed", "Date changed"),
                    ("date_seen_removed", "Date removed"),
                ],
                max_length=40,
            ),
        ),
    ]
