# Generated by Django 5.2.7 on 2026-03-05 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_postmark_moderation_notes_postmark_moderation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users explicitly assigned to this location/state for administration or review', related_name='assigned_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
