# Generated by Django 5.2.7 on 2026-03-11 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_readd_postmark_contribution_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(db_column='ContributionID', primary_key=True, serialize=False)),
                ('submitted_data', models.JSONField(blank=True, db_column='SubmittedData', default=dict, help_text='Proposed changes (state, town, type, color, description, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs revision')], db_column='Status', default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, db_column='ReviewNotes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('contributor', models.ForeignKey(db_column='ContributorUserID', on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('postmark', models.OneToOneField(blank=True, db_column='PostmarkID', help_text='Set when approved; Postmark created from submitted_data for new entries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='common.postmark')),
                ('reviewer', models.ForeignKey(blank=True, db_column='ReviewerUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'db_table': 'Contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
