# Generated by Django 5.2.7 on 2026-03-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_ensure_contributions_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('modified_date', models.DateTimeField(auto_now=True, db_column='ModifiedDate')),
                ('faq_entry_id', models.AutoField(db_column='FAQEntryID', primary_key=True, serialize=False)),
                ('question', models.CharField(db_column='Question', max_length=500)),
                ('answer', models.TextField(db_column='Answer')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('display_order', models.PositiveIntegerField(db_column='DisplayOrder', default=0, help_text='Lower numbers appear first.')),
                ('created_by', models.ForeignKey(db_column='CreatedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(db_column='ModifiedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'db_table': 'FAQEntries',
                'ordering': ['display_order', 'faq_entry_id'],
            },
        ),
    ]
