# Generated by Django 5.2.7 on 2026-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_postmark_catalog_txt_postmark_code_postmark_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='code',
            field=models.CharField(blank=True, db_column='code', help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='framing',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
    ]
