# Generated by Django 5.2.7 on 2026-04-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0039_strip_db_column_overrides'),
    ]

    operations = [
        # These indexes were auto-dropped by MySQL when their underlying FK
        # columns (postal_facility, postmark_key, state) were removed in
        # earlier migrations. Update Django's state only; no DB op needed.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='postmark',
                    name='Postmarks_PostalF_b9397c_idx',
                ),
                migrations.RemoveIndex(
                    model_name='postmark',
                    name='Postmarks_Postmar_c85d2f_idx',
                ),
                migrations.RemoveIndex(
                    model_name='postmark',
                    name='Postmarks_StateID_084a2a_idx',
                ),
            ],
            database_operations=[],
        ),
        migrations.RenameIndex(
            model_name='postcover',
            new_name='Postcovers_owner_u_6b00c9_idx',
            old_name='Postcovers_OwnerUs_3a89ce_idx',
        ),
        migrations.RenameIndex(
            model_name='postcover',
            new_name='Postcovers_postcov_a560c7_idx',
            old_name='Postcovers_Postcov_a79a74_idx',
        ),
        migrations.RenameIndex(
            model_name='postcoverimage',
            new_name='PostcoverIm_postcov_157282_idx',
            old_name='PostcoverIm_Postcov_cb9bda_idx',
        ),
        migrations.RenameIndex(
            model_name='postcoverimage',
            new_name='PostcoverIm_file_ch_22965c_idx',
            old_name='PostcoverIm_FileChe_1473bb_idx',
        ),
        migrations.RenameIndex(
            model_name='postmarkimage',
            new_name='PostmarkIma_postmar_5f6f67_idx',
            old_name='PostmarkIma_Postmar_a95f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='postmarkimage',
            new_name='PostmarkIma_file_ch_be7e3f_idx',
            old_name='PostmarkIma_FileChe_1d7426_idx',
        ),
        migrations.AlterField(
            model_name='postmark',
            name='catalog_txt',
            field=models.TextField(blank=True, help_text='Authoritative catalog entry text for this listing'),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks', to='common.color'),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='date_fmt',
            field=models.CharField(blank=True, choices=[('MD', 'MD'), ('MDD', 'MDD'), ('YD', 'YD'), ('YMD', 'YMD'), ('YMDD', 'YMDD')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='date_type',
            field=models.CharField(blank=True, choices=[('BISHOP MARK', 'Bishop Mark'), ('FRANKLIN MARK', 'Franklin Mark'), ('QUAKER DATE', 'Quaker Date')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='impression',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Stencil', 'Stencil'), ('Negative', 'Negative')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='is_irreg',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='is_manuscript',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='lettering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks', to='common.lettering'),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='postmarks', to='common.shape'),
        ),
        migrations.AlterField(
            model_name='postmark',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
