# Generated by Django 5.2.7 on 2026-04-18 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0040_remove_postmark_postmarks_postalf_b9397c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dateobserved',
            index=models.Index(fields=['postmark', 'date'], name='date_obs_pm_date_idx'),
        ),
    ]
