# Generated by Django 5.2.7 on 2026-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_date_observed_postmark_date_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='auxmark',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ratemark',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
    ]
