# Generated by Django 5.2.7 on 2026-04-30 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_rename_audit_indexes_to_django_default_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Calendar date of the observed use')),
                ('granularity', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month'), ('YEAR', 'Year')], max_length=5)),
            ],
            options={
                'verbose_name': 'Cover Date',
                'verbose_name_plural': 'Cover Dates',
                'db_table': 'cover_date',
                'ordering': ['cover', 'date'],
            },
        ),
        migrations.CreateModel(
            name='CoverMarking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_backstamp', models.BooleanField(default=False, help_text='Whether this marking appears on the reverse of the cover')),
                ('placement', models.CharField(blank=True, help_text='Free-form placement qualifier; vocabulary not yet enumerated', max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Cover Marking',
                'verbose_name_plural': 'Cover Markings',
                'db_table': 'cover_marking',
            },
        ),
        migrations.CreateModel(
            name='CoverValuation',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('cover_valuation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, help_text='Non-negative USD; null = unpriced entry', max_digits=10, null=True)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cover Valuation',
                'verbose_name_plural': 'Cover Valuations',
                'db_table': 'cover_valuation',
                'ordering': ['-appraisal_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('COVER', 'Cover'), ('MARKING', 'Marking')], max_length=8)),
                ('subject_id', models.PositiveIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_filename', models.CharField(max_length=255, unique=True)),
                ('file_checksum', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=64)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('image_view', models.CharField(choices=[('BACK', 'Back'), ('COMPARISON', 'Comparison'), ('DETAIL', 'Detail'), ('FRONT', 'Front'), ('FULL', 'Full'), ('INTERIOR', 'Interior')], max_length=16)),
                ('image_description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
                'ordering': ['subject_type', 'subject_id', 'display_order'],
                'permissions': [('approve_image', 'Can approve / reject image submissions')],
            },
        ),
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('marking_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True)),
                ('type', models.CharField(choices=[('TOWNMARK', 'Townmark'), ('RATEMARK', 'Ratemark'), ('AUXMARK', 'Auxmark')], help_text='Functional classification of this marking', max_length=8)),
                ('catalog_txt', models.TextField(blank=True, help_text='Authoritative ASCC catalog entry text for this listing', null=True)),
                ('inscription_txt', models.TextField(help_text='Text as physically inscribed on the marking')),
                ('desc', models.TextField(blank=True, help_text='Free-text contributor annotation', null=True)),
                ('is_manuscript', models.BooleanField()),
                ('is_irreg', models.BooleanField(blank=True, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='Horizontal dimension in millimeters', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Vertical dimension in millimeters', max_digits=6, null=True)),
                ('date_fmt', models.CharField(blank=True, choices=[('MD', 'MD'), ('MDD', 'MDD'), ('YD', 'YD'), ('YMD', 'YMD'), ('YMDD', 'YMDD')], max_length=10, null=True)),
                ('impression', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Stencil', 'Stencil'), ('Negative', 'Negative')], max_length=10, null=True)),
                ('rate_val', models.DecimalField(blank=True, decimal_places=2, help_text='Non-negative rate amount; most common on RATEMARK and integrated-rate TOWNMARK rows', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Marking',
                'verbose_name_plural': 'Markings',
                'db_table': 'Markings',
                'ordering': ['marking_id'],
            },
        ),
        migrations.CreateModel(
            name='MarkingVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marking Version',
                'verbose_name_plural': 'Marking Versions',
                'db_table': 'MarkingVersions',
                'ordering': ['-version_no', '-id'],
            },
        ),

        # Drop indexes that reference fields about to be removed, before
        # those fields go. Django's autodetector left this RemoveIndex
        # ordered after the RemoveField, which fails state lookup.
        migrations.RemoveIndex(
            model_name='submissiontransaction',
            name='SubmissionT_postmar_e49a38_idx',
        ),

        # Drop every unique_together first so subsequent RemoveField ops do
        # not try to drop columns that the unique-index still references on
        # MySQL. The Django autodetector orders these inconsistently for
        # deleted models, so we hoist them up by hand.
        migrations.AlterUniqueTogether(
            name='coverpostmark',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='markframing',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='postcoverpostmark',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='postmarkratemark',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='postmarkvaluation',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='postmarkversion',
            unique_together=None,
        ),

        migrations.RemoveField(
            model_name='auxmark',
            name='color',
        ),
        migrations.RemoveField(
            model_name='auxmark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='auxmark',
            name='lettering',
        ),
        migrations.RemoveField(
            model_name='auxmark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='auxmark',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='coverpostmark',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='coverpostmark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coverpostmark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='coverpostmark',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='dateobserved',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dateobserved',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='dateobserved',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='framing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='framing',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='markframing',
            name='framing',
        ),
        migrations.RemoveField(
            model_name='markframing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='markframing',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postcoverpostmark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postcoverpostmark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postcoverpostmark',
            name='postcover',
        ),
        migrations.RemoveField(
            model_name='postcoverpostmark',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='color',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='lettering',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='postmark',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='postmarkvaluation',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='postmarkimage',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='postmarkratemark',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='submissiontransaction',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='postmarkversion',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='postmark',
        ),
        migrations.RemoveField(
            model_name='postmarkimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postmarkimage',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postmarkimage',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='postmarkratemark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postmarkratemark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postmarkratemark',
            name='ratemark',
        ),
        migrations.RemoveField(
            model_name='postmarkvaluation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postmarkvaluation',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='postmarkversion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='postmarkversion',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='ratemark',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ratemark',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ratemark',
            name='lettering',
        ),
        migrations.RemoveField(
            model_name='ratemark',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='ratemark',
            name='shape',
        ),
        migrations.AlterField(
            model_name='citation',
            name='subject_id',
            field=models.PositiveIntegerField(help_text='PK of the referenced Cover or Marking'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='subject_type',
            field=models.CharField(choices=[('COVER', 'Cover'), ('MARKING', 'Marking')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='citation',
            constraint=models.CheckConstraint(condition=models.Q(('subject_type__in', ['COVER', 'MARKING'])), name='citation_subject_type_valid'),
        ),
        migrations.AddField(
            model_name='coverdate',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_dates', to='common.cover'),
        ),
        migrations.AddField(
            model_name='coverdate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverdate',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covermarking',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_markings', to='common.cover'),
        ),
        migrations.AddField(
            model_name='covermarking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covermarking',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covervaluation',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='common.cover'),
        ),
        migrations.AddField(
            model_name='covervaluation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='covervaluation',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marking',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='markings', to='common.color'),
        ),
        migrations.AddField(
            model_name='marking',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marking',
            name='lettering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='markings', to='common.lettering'),
        ),
        migrations.AddField(
            model_name='marking',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marking',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markings', to='common.postoffice'),
        ),
        migrations.AddField(
            model_name='marking',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='markings', to='common.shape'),
        ),
        migrations.AddField(
            model_name='covermarking',
            name='marking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_markings', to='common.marking'),
        ),
        migrations.CreateModel(
            name='CatalogRequestMarking',
            fields=[
            ],
            options={
                'verbose_name': 'Catalog request',
                'verbose_name_plural': 'Catalog requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.marking',),
        ),
        migrations.AddField(
            model_name='contribution',
            name='marking',
            field=models.OneToOneField(blank=True, help_text='Set when approved; Marking created from submitted_data for new entries', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution', to='common.marking'),
        ),
        migrations.AddField(
            model_name='submissiontransaction',
            name='marking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='common.marking'),
        ),
        migrations.AddIndex(
            model_name='submissiontransaction',
            index=models.Index(fields=['marking', 'created_at'], name='SubmissionT_marking_742924_idx'),
        ),
        migrations.AddField(
            model_name='markingversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markingversion',
            name='marking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='common.marking'),
        ),
        migrations.AddField(
            model_name='markingversion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='common.submissiontransaction'),
        ),
        migrations.DeleteModel(
            name='Auxmark',
        ),
        migrations.DeleteModel(
            name='CoverPostmark',
        ),
        migrations.DeleteModel(
            name='DateObserved',
        ),
        migrations.DeleteModel(
            name='Framing',
        ),
        migrations.DeleteModel(
            name='MarkFraming',
        ),
        migrations.DeleteModel(
            name='PostcoverPostmark',
        ),
        migrations.DeleteModel(
            name='Postmark',
        ),
        migrations.DeleteModel(
            name='PostmarkImage',
        ),
        migrations.DeleteModel(
            name='PostmarkRatemark',
        ),
        migrations.DeleteModel(
            name='PostmarkValuation',
        ),
        migrations.DeleteModel(
            name='PostmarkVersion',
        ),
        migrations.DeleteModel(
            name='Ratemark',
        ),
        migrations.AddIndex(
            model_name='coverdate',
            index=models.Index(fields=['cover', 'date'], name='cover_date_cover_date_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['subject_type', 'subject_id', 'display_order'], name='images_subject_f2f8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['file_checksum'], name='images_file_ch_e14c0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_view__in', ['FULL', 'DETAIL', 'COMPARISON']), ('subject_type', 'MARKING')), models.Q(('image_view__in', ['FRONT', 'BACK', 'INTERIOR', 'DETAIL']), ('subject_type', 'COVER')), _connector='OR'), name='image_view_matches_subject_type'),
        ),
        migrations.AddConstraint(
            model_name='marking',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['TOWNMARK', 'RATEMARK', 'AUXMARK'])), name='marking_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='marking',
            constraint=models.CheckConstraint(condition=models.Q(('date_fmt__isnull', True), ('date_fmt__in', ['MD', 'MDD', 'YD', 'YMD', 'YMDD']), _connector='OR'), name='marking_date_fmt_valid'),
        ),
        migrations.AddConstraint(
            model_name='marking',
            constraint=models.CheckConstraint(condition=models.Q(('impression__isnull', True), ('impression__in', ['Normal', 'Stencil', 'Negative']), _connector='OR'), name='marking_impression_valid'),
        ),
        migrations.AddConstraint(
            model_name='marking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_irreg__isnull', True), ('is_manuscript', True), ('lettering__isnull', True), ('shape__isnull', True)), models.Q(('is_irreg__isnull', False), ('is_manuscript', False), ('shape__isnull', False)), _connector='OR'), name='marking_manuscript_consistency'),
        ),
        migrations.AlterUniqueTogether(
            name='covermarking',
            unique_together={('cover', 'marking')},
        ),
        migrations.AddIndex(
            model_name='markingversion',
            index=models.Index(fields=['marking', 'version_no'], name='MarkingVers_marking_83036c_idx'),
        ),
        migrations.AddIndex(
            model_name='markingversion',
            index=models.Index(fields=['created_at'], name='MarkingVers_created_5aed5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='markingversion',
            unique_together={('marking', 'version_no')},
        ),
    ]
