# Generated by Django 5.2.7 on 2026-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_unify_markings'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencework',
            name='code',
            field=models.CharField(blank=True, help_text='Editor-assigned reference identifier', max_length=30, null=True, unique=True),
        ),
    ]
