# Generated by hand on 2026-05-03.
#
# Standardize the v2 catalog PKs onto Django's default name `id`.
# Color.color_id, Marking.marking_id, and CoverValuation.cover_valuation_id
# were the only three v2 catalog models declaring custom PK column names;
# every other v2 catalog model already uses `id`. RenameField preserves
# the existing AutoField (INT) column and the integer ids of every row.
# FK constraints from related tables are updated by Django automatically.
#
# This migration must use RenameField, not RemoveField + AddField (which
# would drop and recreate the PK column, destroying data and re-pointing
# every dependent FK at id 1). `makemigrations` did not detect the rename
# automatically because the change crosses primary_key=True boundaries,
# so this file is hand-written.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0058_referencework_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='marking',
            old_name='marking_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='covervaluation',
            old_name='cover_valuation_id',
            new_name='id',
        ),
        migrations.AlterModelOptions(
            name='marking',
            options={
                'ordering': ['id'],
                'verbose_name': 'Marking',
                'verbose_name_plural': 'Markings',
            },
        ),
    ]
