# Generated by Django 5.2.7 on 2026-05-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_v2_pk_standardize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminCsvUpload',
        ),
    ]
