# Generated by Django 5.2.7 on 2026-05-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0065_alter_postofficeregion_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyAbbreviation',
        ),
        migrations.DeleteModel(
            name='LegacyCover',
        ),
        migrations.DeleteModel(
            name='LegacyParseStep',
        ),
        migrations.DeleteModel(
            name='LegacyRateLocation',
        ),
        migrations.DeleteModel(
            name='LegacyRateValue',
        ),
        migrations.DeleteModel(
            name='LegacyRawStateDataPendingUpdate',
        ),
        migrations.DeleteModel(
            name='LegacyUserState',
        ),
    ]
