# Generated by Django 5.2.7 on 2026-05-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0066_drop_legacy_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='storage_filename',
            field=models.CharField(max_length=255),
        ),
    ]
