# Generated by Django 5.2.7 on 2026-05-17 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0067_image_storage_filename_drop_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostcoverImage',
        ),
    ]
