# Generated by Django 5.2.7 on 2026-05-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0068_alter_covermarking_contributor_comment_nullable'),
        ('common', '0068_drop_postcover_image'),
    ]

    operations = [
    ]
