# Generated by Django 5.2.7 on 2026-05-22 14:55

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0069_grubermeister_merger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marking',
            options={'base_manager_name': 'all_objects', 'ordering': ['id'], 'verbose_name': 'Marking', 'verbose_name_plural': 'Markings'},
        ),
        migrations.AlterModelManagers(
            name='marking',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='submissiontransaction',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('edit_submission', 'Edit submission'), ('editor_edit', 'Editor edit'), ('approve', 'Approve'), ('reject', 'Reject'), ('catalog_direct_edit', 'Catalog direct edit'), ('restore_version', 'Restore version'), ('record_create', 'Record create'), ('record_update', 'Record update'), ('record_delete', 'Record delete'), ('draft_deleted', 'Draft deleted'), ('marking_removed', 'Marking removed'), ('marking_restored', 'Marking restored')], max_length=40),
        ),
        migrations.CreateModel(
            name='MarkingRecycleBin',
            fields=[
                ('marking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recycle_bin_entry', serialize=False, to='common.marking')),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('removed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markings_removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recycle-binned Marking',
                'verbose_name_plural': 'Recycle-binned Markings',
                'db_table': 'marking_recycle_bin',
                'ordering': ['-removed_at'],
                'indexes': [models.Index(fields=['removed_at'], name='marking_rec_removed_b7690d_idx')],
            },
        ),
    ]
