# Generated by Django 5.2.7 on 2026-05-24 15:00

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0070_alter_marking_options_alter_marking_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverRecycleBin',
            fields=[
                ('cover', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recycle_bin_entry', serialize=False, to='common.cover')),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Recycle-binned Cover',
                'verbose_name_plural': 'Recycle-binned Covers',
                'db_table': 'cover_recycle_bin',
                'ordering': ['-removed_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cover Version',
                'verbose_name_plural': 'Cover Versions',
                'db_table': 'CoverVersions',
                'ordering': ['-version_no', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={'base_manager_name': 'all_objects', 'ordering': ['id'], 'verbose_name': 'Cover', 'verbose_name_plural': 'Covers'},
        ),
        migrations.AlterModelManagers(
            name='cover',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='submissiontransaction',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='common.cover'),
        ),
        migrations.AlterField(
            model_name='submissiontransaction',
            name='action',
            field=models.CharField(choices=[('submit', 'Submit'), ('edit_submission', 'Edit submission'), ('editor_edit', 'Editor edit'), ('approve', 'Approve'), ('reject', 'Reject'), ('catalog_direct_edit', 'Catalog direct edit'), ('restore_version', 'Restore version'), ('record_create', 'Record create'), ('record_update', 'Record update'), ('record_delete', 'Record delete'), ('draft_deleted', 'Draft deleted'), ('marking_removed', 'Marking removed'), ('marking_restored', 'Marking restored'), ('cover_removed', 'Cover removed'), ('cover_restored', 'Cover restored')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='submissiontransaction',
            index=models.Index(fields=['cover', 'created_at'], name='SubmissionT_cover_i_4338af_idx'),
        ),
        migrations.AddField(
            model_name='coverrecyclebin',
            name='removed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covers_removed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverversion',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='common.cover'),
        ),
        migrations.AddField(
            model_name='coverversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coverversion',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_versions', to='common.submissiontransaction'),
        ),
        migrations.AddIndex(
            model_name='coverrecyclebin',
            index=models.Index(fields=['removed_at'], name='cover_recyc_removed_4e3e70_idx'),
        ),
        migrations.AddIndex(
            model_name='coverversion',
            index=models.Index(fields=['cover', 'version_no'], name='CoverVersio_cover_i_a5fa59_idx'),
        ),
        migrations.AddIndex(
            model_name='coverversion',
            index=models.Index(fields=['created_at'], name='CoverVersio_created_ac7985_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coverversion',
            unique_together={('cover', 'version_no')},
        ),
    ]
