# APMC SOURCE DATA EXPLORER

This notebook provides analytical approaches for exploring the `tblRawStateData` table and its parsed fields to determine optimal database normalization strategy from the original ASCC catalog data.  

> The real value resides in well-parsed descriptive text fields from original catalog sources rather than elaborate normalized structures that often remain unused.

## Contents
[0. Setup and Data Loading](#0-Setup-and-Data-Loading) - _Load CSV data and configure display settings_

[1. Field Survey](#1-Field-Survey) - _Population rates and cardinality across all columns to identify natural field groupings_

[2. Source Text Structure](#2-Source-Text-Structure) - _Extract structural patterns from txtRawStateData to understand formatting consistency_

[3. The Two-Tier Architecture](#3-The-Two-Tier-Architecture) - _Establish and validate the Layer 1 (parsed) vs Layer 2 (classified) data entry pattern_

[4. Normalization Trade-off Analysis](#4-Normalization-Trade-off-Analysis) - _Evaluate cost/benefit of different normalization approaches_

[5. Philatelic-Specific Analysis](#5-Philatelic-Specific-Analysis) - _Domain-specific explorations: town names, dates, colors, sizes_

6\. Specific Issue Investigation:
   - [6.1. Geographic Coverage Analysis](#61-Geographic-Coverage-Analysis) - _State-by-state record distribution_
   - [6.2. Color Handling Ambiguity Analysis](#62-Color-Handling-Ambiguity-Analysis) - _Investigate multi-color notation semantics and ASCC documentation gaps_
   - [6.3. Relationship Indicator Interpretation Evidence](#63-Relationship-Indicator-Interpretation-Evidence) - _Empirical validation that Same/(L)/(E) markers indicate parent-child inheritance_
   - [6.4. Date Field vs txtDatesSeen Validation](#64-Date-Field-vs-txtDatesSeen-Validation) - _Verify earliest/latest date fields align with source date text_
   - [6.5. Is postmark_dateseen a Required Table?](#65-is-postmark_dateseen-a-required-table) - _Determine whether a 1:many date observation table is warranted by the source data_
   - [6.6. Size Field vs txtSizes Validation](#66-size-field-vs-txtsizes-validation)
   - [6.7. txtValue Normalization Candidacy](#67-txtvalue-normalization-candidacy) - _Assess whether slash-separated valuations warrant a child table_
   

[7. Summary & Recommendations](#7-Summary--Recommendations) - _Final normalization recommendations_


## 0. Setup and Data Loading

In [3]:
import pandas as pd
import numpy as np
import re
from collections import Counter
from pathlib import Path

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 100)

In [4]:
# Load the main data file
# Adjust path as needed for your environment
CSV_PATH = "./wip/in/tblRawStateData_orig.csv"

print("Loading data...")
df = pd.read_csv(CSV_PATH, low_memory=False, keep_default_na=False)
print(f"Loaded {len(df):,} records with {len(df.columns)} columns")

# Uncomment to filter only to approved, non-deleted records
#approved = df[(df['ynDeleted'] == 0) & (df['approve_status'] == 'Approved')].copy()
#print(f"Approved, non-deleted records: {len(approved):,}")
#df = approved

Loading data...
Loaded 52,046 records with 62 columns


---
## 1. Field Survey

Before making normalization decisions, we need to understand the full landscape of fields in `tblRawStateData`. This section surveys all columns to identify natural groupings, population patterns, and cardinality characteristics — letting the data tell us which fields deserve deeper analysis.


In [5]:
# Quick overview of columns
print("Columns in dataset:")
for i, col in enumerate(df.columns):
    print(f"  {i:2}. {col}")

Columns in dataset:
   0. nRawStateDataID
   1. nRawStateDataID_parent
   2. nGroupOrder
   3. nStateID
   4. txtRawStateData
   5. txtRawStateDataTemp
   6. txtWorkingData
   7. txtPostmark
   8. txtDatesSeen
   9. txtSizes
  10. txtColors
  11. txtRates
  12. txtRatesText
  13. txtValue
  14. txtTerritory
  15. txtTown
  16. txtTownPostmark
  17. txtTownmarkShape
  18. txtTownmarkLettering
  19. txtTownmarkDateFormat
  20. txtTownmarkFraming
  21. txtTownmarkRateLocation
  22. txtTownmarkRateText
  23. txtTownmarkRateValue
  24. txtTownmarkColor
  25. nWidth
  26. nHeight
  27. txtOther
  28. ynEarliestKnownDate
  29. ynLatestKnownDate
  30. nEarliestUseDay
  31. txtEarliestUseMonth
  32. txtEarliestUseYear
  33. nEarliestUseYear
  34. nLatestUseDay
  35. txtLatestUseMonth
  36. nLatestUseYear
  37. txtLatestUseYear
  38. ynManuscript
  39. ynBackstamp
  40. txtPublishedID
  41. txtDefaultImage
  42. txtPDFPage
  43. ynProcessed
  44. memNotes
  45. ynTownNameHasExtra
  46. ynManuscr

### 1.1 Column Naming Conventions

The column names follow a consistent prefix convention that reveals the table's design intent:

- **`n*`** — Numeric identifiers and measurements (`nRawStateDataID`, `nWidth`, `nHeight`, `nEarliestUseYear`, etc.)
- **`txt*`** — Text data fields, which subdivide further (see below)
- **`yn*`** — Boolean flags (`ynManuscript`, `ynBackstamp`, `ynDeleted`, etc.)
- **`dt*`** — Timestamps (`dtEntered`, `dtUpdated`)
- **`mem*`** — Memo/notes fields (`memNotes`)

Within the `txt*` fields, there is a notable split: some carry a **`txtTownmark`** prefix (e.g., `txtTownmarkShape`, `txtTownmarkLettering`, `txtTownmarkColor`) while others do not (e.g., `txtPostmark`, `txtColors`, `txtDatesSeen`, `txtRatesText`). Whether this naming distinction corresponds to a meaningful difference in population, cardinality, or data entry workflow is the central question of this survey.


### 1.2 Field Population Rates

Population rates reveal which fields are consistently filled versus sparsely used. This is the first step toward understanding whether certain field groups reflect different data entry phases or purposes.


In [6]:
def field_population_report(df, exclude_system_cols=True):
    """
    Generate population rates for all fields.
    Helps identify which fields are essential vs sparsely used.
    """
    system_cols = ['dtEntered', 'dtUpdated', 'ynActive', 'ynDeleted', 'nOrder']
    
    results = []
    for col in df.columns:
        if exclude_system_cols and col in system_cols:
            continue
            
        non_null = df[df[col].notna()]
        
        # Also exclude 'NULL' strings and empty strings
        if df[col].dtype == 'object':
            non_null = non_null[
                (non_null[col] != 'NULL') & 
                (non_null[col] != '') &
                (non_null[col] != 'n/a') &
                (non_null[col] != '--')
            ]
        
        results.append({
            'column': col,
            'dtype': str(df[col].dtype),
            'populated': len(non_null),
            'population_rate': len(non_null) / len(df) * 100,
            'unique_values': non_null[col].nunique() if len(non_null) > 0 else 0
        })
    
    report = pd.DataFrame(results).sort_values('population_rate', ascending=False)
    return report

In [7]:
def essential_vs_sparse_fields(df, threshold=50):
    """
    Categorize fields into essential (>threshold%) vs sparse (<threshold%).
    """
    report = field_population_report(df)
    
    essential = report[report['population_rate'] >= threshold]
    sparse = report[report['population_rate'] < threshold]
    
    print(f"\n{'='*60}")
    print(f"ESSENTIAL FIELDS (>{threshold}% populated)")
    print(f"{'='*60}")
    display(essential[['column', 'population_rate', 'unique_values']])
    
    print(f"\n{'='*60}")
    print(f"SPARSE FIELDS (<{threshold}% populated)")
    print(f"{'='*60}")
    display(sparse[['column', 'population_rate', 'unique_values']])
    
    return essential, sparse

In [8]:
# Run field population analysis
essential, sparse = essential_vs_sparse_fields(df, threshold=30)


ESSENTIAL FIELDS (>30% populated)


,column,population_rate,unique_values
0,nRawStateDataID,100.000000,52046
28,ynEarliestKnownDate,100.000000,2
52,approve_status,100.000000,4
48,ynForReview,100.000000,2
47,nImageCount,100.000000,14
46,ynManuscriptTownmarks,100.000000,2
45,ynTownNameHasExtra,100.000000,2
43,ynProcessed,100.000000,2
39,ynBackstamp,100.000000,2
38,ynManuscript,100.000000,2



SPARSE FIELDS (<30% populated)


,column,population_rate,unique_values
12,txtRatesText,26.553434,3387
41,txtDefaultImage,12.581178,6548
24,txtTownmarkColor,9.510817,131
33,nEarliestUseYear,7.575990,137
18,txtTownmarkLettering,7.203243,4
32,txtEarliestUseYear,6.667179,409
36,nLatestUseYear,5.131999,133
25,nWidth,3.879261,73
37,txtLatestUseYear,2.834031,121
31,txtEarliestUseMonth,2.768705,40


### 1.3 Two Populations of Text Fields

The population report above reveals a striking pattern within the `txt*` content fields. They fall into two distinct groups:

**Group A — Moderate-to-high population (2–83%):** Fields like `txtPostmark` (~83%), `txtDatesSeen` (~81%), `txtColors` (~45%), `txtSizes` (~41%), `txtRatesText` (~27%), and `txtValue` (~82%). These store parsed extracts from `txtRawStateData` in the ASCC's own notation — compact, semi-structured text that preserves the catalog's conventions.

**Group B — Uniformly sparse (0.3–9%):** Fields sharing the `txtTownmark*` prefix: `txtTownmarkShape` (~2.7%), `txtTownmarkLettering` (~7.2%), `txtTownmarkColor` (~9.5%), `txtTownmarkDateFormat` (~0.8%), `txtTownmarkFraming` (~0.6%), `txtTownmarkRateLocation` (~0.3%), `txtTownmarkRateValue` (~0.3%). These store controlled-vocabulary classifications using plain English terms like "Circle", "Normal", "NOR".

The population gap is not a matter of degree — it is an order-of-magnitude difference that correlates perfectly with the naming prefix. This suggests the two groups reflect **different data entry phases**: one automated or semi-automated import from catalog text, and one requiring manual expert judgment that was never completed across the full dataset.

The cardinality analysis below tests whether the sparse `txtTownmark*` group also differs in its value characteristics.


### 1.4 Cardinality Analysis: The Sparse `txtTownmark*` Group

If the sparse `txtTownmark*` fields represent controlled-vocabulary classification (as their values suggest), we would expect:
- Low cardinality (few unique values relative to records)
- High concentration (a small number of values covering most records)
- Values that look like enumerated categories, not free text


In [9]:
def cardinality_analysis(df, columns_of_interest):
    """
    Analyze fields to determine normalization candidates.
    
    Key metrics:
    - Unique count vs total records
    - Frequency distribution
    - Top N values coverage percentage
    """
    results = []
    total_records = len(df)
    
    for col in columns_of_interest:
        non_null = df[df[col].notna() & (df[col] != '') & (df[col] != 'NULL')]
        populated_count = len(non_null)
        unique_values = non_null[col].nunique()
        
        if populated_count > 0:
            # Top 10 values coverage
            value_counts = non_null[col].value_counts()
            top_10_coverage = value_counts.head(10).sum() / populated_count * 100
            top_25_coverage = value_counts.head(25).sum() / populated_count * 100
            
            # Concentration ratio (does a small set dominate?)
            concentration = value_counts.head(5).sum() / populated_count * 100
            
            results.append({
                'column': col,
                'total_records': total_records,
                'populated_count': populated_count,
                'population_rate': populated_count / total_records * 100,
                'unique_values': unique_values,
                'cardinality_ratio': unique_values / populated_count,
                'top_10_coverage_pct': top_10_coverage,
                'top_20_coverage_pct': top_25_coverage,
                'top_5_concentration_pct': concentration,
                'normalization_candidate': unique_values < 100 and concentration > 50
            })
    
    return pd.DataFrame(results)

In [10]:
def examine_value_distribution(df, column):
    """
    Deep dive into a specific column's value distribution.
    Useful for understanding if a controlled vocabulary fits.
    """
    non_null = df[df[column].notna() & (df[column] != '') & (df[column] != 'NULL')]
    
    print(f"\n{'='*60}")
    print(f"Value Distribution: {column}")
    print(f"{'='*60}")
    print(f"Total records: {len(df):,}")
    print(f"Populated: {len(non_null):,} ({len(non_null)/len(df)*100:.1f}%)")
    print(f"Unique values: {non_null[column].nunique():,}")
    print(f"\nAll unique values:")
    print(non_null[column].value_counts().to_string())
    
    return non_null[column].value_counts()

In [11]:
# Run cardinality analysis on the sparse txtTownmark* fields
# These fields were identified in §1.3 by their shared naming prefix and
# uniformly low population rates — NOT pre-selected for this analysis.
classification_cols = [
    'txtTownmarkShape', 'txtTownmarkLettering', 'txtTownmarkDateFormat',
    'txtTownmarkFraming','txtTownmarkColor'
]

cardinality_df = cardinality_analysis(df, classification_cols)
cardinality_df


,column,total_records,populated_count,population_rate,unique_values,cardinality_ratio,top_10_coverage_pct,top_20_coverage_pct,top_5_concentration_pct,normalization_candidate
0,txtTownmarkShape,52046,1714,3.293241,26,0.015169,95.215869,99.883314,85.064177,True
1,txtTownmarkLettering,52046,3749,7.203243,4,0.001067,100.000000,100.000000,100.000000,True
2,txtTownmarkDateFormat,52046,3140,6.033125,12,0.003822,99.363057,100.000000,94.490446,True
3,txtTownmarkFraming,52046,941,1.808016,11,0.011690,99.893730,100.000000,96.174283,True
4,txtTownmarkColor,52046,5126,9.848980,132,0.025751,92.645337,96.800624,83.378853,False


In [12]:
# Deep dive into specific fields
for col in cardinality_df[cardinality_df['normalization_candidate'] == True]['column']:
    examine_value_distribution(df, col)


Value Distribution: txtTownmarkShape
Total records: 52,046
Populated: 1,714 (3.3%)
Unique values: 26

All unique values:
txtTownmarkShape
Straight line             520
Circle                    418
n/a                       291
Double Circle             143
Arc                        86
Oval                       78
Box                        42
Double Oval                19
Double Line Circle         19
Octagon                    16
Fancy/morticed             12
Dashed Circle               9
Pictoral                    8
Shell Design                7
Dotted Oval                 6
Straight Line               5
Geometric (not circle)      5
Framed Arc                  4
Fancy Oval                  4
Fancy Box                   4
Double Lined Box            4
Double Line Oval            4
Tombstone                   3
Straight line - 2 line      3
Dotted Circle               2
Straight line - 3 line      2

Value Distribution: txtTownmarkLettering
Total records: 52,046
Populated: 3,749 

### 1.5 Cardinality Contrast: Parsed Text Fields (Group A)

For comparison, the same cardinality analysis on representative Group A fields shows the opposite profile — high cardinality, free-text values, no controlled vocabulary.


In [13]:
# Contrast: cardinality analysis on Group A (parsed text) fields
# These are the moderate-to-high population fields from §1.3
parsed_text_cols = [
    'txtColors', 'txtSizes', 'txtRatesText', 'txtDatesSeen', 'txtOther'
]

parsed_cardinality_df = cardinality_analysis(df, parsed_text_cols)
parsed_cardinality_df


,column,total_records,populated_count,population_rate,unique_values,cardinality_ratio,top_10_coverage_pct,top_20_coverage_pct,top_5_concentration_pct,normalization_candidate
0,txtColors,52046,23357,44.877608,376,0.016098,93.316779,96.014043,83.024361,False
1,txtSizes,52046,21397,41.111709,3036,0.141889,62.719073,69.864934,50.965089,False
2,txtRatesText,52046,13827,26.566883,3388,0.245028,43.487380,54.068128,34.823172,False
3,txtDatesSeen,52046,42503,81.664297,9382,0.220737,19.509211,29.388514,12.434416,False
4,txtOther,52046,1148,2.205741,490,0.426829,25.522648,42.073171,14.982578,False


### 1.6 Field Survey Summary

The data reveals two distinct populations of content fields, which we will call **Layer 1** and **Layer 2**:

| Characteristic | Layer 1 (Parsed Text) | Layer 2 (`txtTownmark*` Classification) |
|---|---|---|
| Population | 2–83% | 0.3–9% |
| Cardinality | High (hundreds to thousands of unique values) | Low (4–93 unique values) |
| Value style | Free text preserving ASCC notation | Controlled vocabulary categories |
| Naming prefix | Various (`txtPostmark`, `txtColors`, etc.) | `txtTownmark*` |
| Normalization candidate? | No — preserve as text | Yes — lookup tables justified |

This distinction drives all downstream normalization decisions. Section 3 will investigate *why* this pattern exists by examining field pairs that capture the same information from both layers.

Additionally, `txtTown` and `txtTownPostmark` occupy a middle ground — they are derived fields with high population (~85–90%) that resolve relationship indicator inheritance and normalize postmark text. They belong to neither pure layer.


### 1.7 Image Count Integrity Check

Verify that the `nImageCount` field accurately reflects the number of related image records in `tblTownmarkImages`. This ensures referential integrity between catalog records and their associated cover images.

In [14]:
# Load townmark images
df_images = pd.read_csv('./wip/in/tblTownmarkImages_orig.csv', keep_default_na=False)
print(f"\nTotal townmark image records: {len(df_images):,}")

# Count images per RawStateData record
actual_image_counts = df_images.groupby('nRawStateDataID').size().reset_index(name='actual_count')

# Merge with RawStateData to compare
comparison = df.merge(
    actual_image_counts, 
    left_on='nRawStateDataID', 
    right_on='nRawStateDataID', 
    how='left'
)

# Fill NaN with 0 for records with no images
comparison['actual_count'] = comparison['actual_count'].fillna(0).astype(int)

# Check for mismatches
comparison['count_mismatch'] = comparison['nImageCount'] != comparison['actual_count']

# Summary statistics
print(f"\nRecords with images in tblTownmarkImages: {len(actual_image_counts):,}")
print(f"Records in tblRawStateData with nImageCount > 0: {(df['nImageCount'] > 0).sum():,}")

mismatches = comparison[comparison['count_mismatch']]
print(f"\nImage count mismatches found: {len(mismatches):,}")

if len(mismatches) > 0:
    print("\nMismatch breakdown:")
    print(f"  Records where nImageCount > actual: {(mismatches['nImageCount'] > mismatches['actual_count']).sum():,}")
    print(f"  Records where nImageCount < actual: {(mismatches['nImageCount'] < mismatches['actual_count']).sum():,}")
    
    print("\nMismatches:")
    print(mismatches[['nRawStateDataID', 'nImageCount', 'actual_count']])
else:
    print("\n All image counts match!")


Total townmark image records: 11,022

Records with images in tblTownmarkImages: 6,640
Records in tblRawStateData with nImageCount > 0: 6,521

Image count mismatches found: 477

Mismatch breakdown:
  Records where nImageCount > actual: 0
  Records where nImageCount < actual: 477

Mismatches:
       nRawStateDataID  nImageCount  actual_count
102                104            0             1
114                116            1             2
151                153            5             6
156                158            4             5
181                183            0             1
...                ...          ...           ...
51655            54599            0             4
51661            54605            2             3
51669            54613            4             5
51748           183740            3             4
51813           183805            2             3

[477 rows x 3 columns]


### 1.8 Default Image Integrity Check

Verify that `txtDefaultImage` values reference actual image filenames in `tblTownmarkImages` for the corresponding record, and that those referenced images are properly marked with `ynMainImage = 1`.

In [15]:
# Filter to records with a default image specified
has_default = df[df['txtDefaultImage'].notna() & (df['txtDefaultImage'] != '')].copy()
print(f"\nRecords with txtDefaultImage specified: {len(has_default):,}")

# Join with images table to check if the default image exists
default_check = has_default.merge(
    df_images[['nRawStateDataID', 'txtFilename', 'ynMainImage']],
    left_on=['nRawStateDataID', 'txtDefaultImage'],
    right_on=['nRawStateDataID', 'txtFilename'],
    how='left',
    indicator=True
)

# Analyze results
image_found = default_check['_merge'] == 'both'
image_not_found = default_check['_merge'] == 'left_only'

print(f"\nDefault image file exists in tblTownmarkImages: {image_found.sum():,}")
print(f"Default image file NOT FOUND in tblTownmarkImages: {image_not_found.sum():,}")

if image_found.sum() > 0:
    # Check ynMainImage flag for found images
    found_images = default_check[image_found]
    main_image_set = found_images['ynMainImage'] == 1
    main_image_not_set = found_images['ynMainImage'] != 1
    
    print(f"\nOf images found:")
    print(f"  Correctly marked as main image (ynMainImage=1): {main_image_set.sum():,}")
    print(f"  NOT marked as main image (ynMainImage != 1): {main_image_not_set.sum():,}")
    
    if main_image_not_set.sum() > 0:
        print("\nCases where default image exists but ynMainImage != 1:")
        print(found_images[main_image_not_set][['nRawStateDataID', 'txtDefaultImage', 'ynMainImage']])

if image_not_found.sum() > 0:
    print("\nCases where txtDefaultImage file not found:")
    not_found = default_check[image_not_found]
    print(not_found[['nRawStateDataID', 'txtTown', 'txtDefaultImage']])


Records with txtDefaultImage specified: 51,956

Default image file exists in tblTownmarkImages: 6,548
Default image file NOT FOUND in tblTownmarkImages: 45,408

Of images found:
  Correctly marked as main image (ynMainImage=1): 6,520
  NOT marked as main image (ynMainImage != 1): 28

Cases where default image exists but ynMainImage != 1:
       nRawStateDataID          txtDefaultImage  ynMainImage
6340              6355      Marking-6355-94.JPG          0.0
6364              6379      Marking-6379-56.JPG          0.0
6513              6529     Marking-6529-128.JPG          0.0
6615              6635     Marking-6635-146.JPG          0.0
6642              6662     Marking-6662-149.JPG          0.0
6658              6679     Marking-6679-150.JPG          0.0
6686              6708     Marking-6708-153.JPG          0.0
6703              6725     Marking-6725-158.JPG          0.0
6715              6737     Marking-6737-161.JPG          0.0
6739              6761     Marking-6761-316.jpg  

---
## 2. Source Text Structure

**Purpose**: Understand the format of `txtRawStateData` — the authoritative ASCC catalog text from which Layer 1 fields were parsed. This establishes the source format that the parsing layer operated on and shows what information is embedded in the raw text.


In [16]:
def extract_raw_data_components(raw_text):
    """
    Parse a txtRawStateData value into component parts.
    
    Typical format example:
    - "Alexa.(Alexandria)(E)(May 21, 1772;Ms;Black) 1,500"
    - "FREDERICKSBURG(\"F\" 5mm high, used as bkstp)(March 1, 1775;SL-50x3,MDD below;Black,Red) 1,200"
    - "(L)(June 27, 1775) 1,000"
    
    Components:
    - Town postmark text
    - Town name (if different from postmark)
    - (E) = Earliest known, (L) = Latest known
    - Date range
    - Size specifications (SL-50x3 = Straight Line 50mm x 3mm)
    - Date format (MDD = Month-Day-Day)
    - Colors
    - Value
    """
    if pd.isna(raw_text) or raw_text == 'NULL':
        return None
    
    components = {
        'raw': raw_text,
        'has_earliest_marker': '(E)' in raw_text,
        'has_latest_marker': '(L)' in raw_text,
        'has_backstamp': 'backstamp' in raw_text.lower() or 'bkstp' in raw_text.lower(),
        'has_manuscript': 'Ms' in raw_text,
        'has_size_spec': bool(re.search(r'SL-\d+x[\d.]+', raw_text)),
        'has_circle': bool(re.search(r'C-\d+', raw_text)),
        'has_value': bool(re.search(r'\s[\d,]+$', raw_text.strip())),
    }
    
    # Extract size specifications
    size_match = re.search(r'(SL|C)-(\d+)x([\d.]+)', raw_text)
    if size_match:
        components['shape'] = 'Straight line' if size_match.group(1) == 'SL' else 'Circle'
        components['width'] = float(size_match.group(2))
        components['height'] = float(size_match.group(3))
    
    # Extract colors (common patterns)
    color_pattern = r';(Black|Red|Blue|Brown|Green|Orange|Magenta)(?:,|[)\]])'
    colors = re.findall(color_pattern, raw_text, re.IGNORECASE)
    components['colors'] = colors
    
    # Extract value
    value_match = re.search(r'\s([\d,]+)$', raw_text.strip())
    if value_match:
        components['value'] = value_match.group(1).replace(',', '')
    
    return components

In [17]:
def pattern_frequency_analysis(df, column='txtRawStateData', sample_size=None):
    """
    Analyze patterns in the raw data to understand formatting consistency.
    This helps determine what parsing rules will work across the dataset.
    """
    data = df[df[column].notna() & (df[column] != 'NULL')][column]
    
    if sample_size and len(data) > sample_size:
        data = data.sample(sample_size)
    
    patterns = {
        'has_parenthetical_name': 0,  # Town(Full Name)
        'has_E_marker': 0,
        'has_L_marker': 0,
        'has_backstamp': 0,
        'has_manuscript': 0,
        'has_SL_size': 0,
        'has_circle_size': 0,
        'has_trailing_value': 0,
        'has_color_spec': 0,
        'has_date_format_spec': 0,  # MDD, MD, YMDD, etc.
    }
    
    for text in data:
        if re.search(r'\([A-Z][a-z]+.*?\)', text):
            patterns['has_parenthetical_name'] += 1
        if '(E)' in text:
            patterns['has_E_marker'] += 1
        if '(L)' in text:
            patterns['has_L_marker'] += 1
        if re.search(r'backstamp|bkstp', text, re.I):
            patterns['has_backstamp'] += 1
        if ';Ms;' in text or ';Ms,' in text:
            patterns['has_manuscript'] += 1
        if re.search(r'SL-\d+', text):
            patterns['has_SL_size'] += 1
        if re.search(r'C-\d+', text):
            patterns['has_circle_size'] += 1
        if re.search(r'\s[\d,]+$', text.strip()):
            patterns['has_trailing_value'] += 1
        if re.search(r';(Black|Red|Blue|Brown|Green)', text, re.I):
            patterns['has_color_spec'] += 1
        if re.search(r'MDD|MD |YMDD|YMD ', text):
            patterns['has_date_format_spec'] += 1
    
    total = len(data)
    print(f"\nPattern Frequency Analysis (n={total:,})")
    print("="*50)
    
    results = []
    for pattern, count in sorted(patterns.items(), key=lambda x: -x[1]):
        pct = count/total*100
        print(f"{pattern:30} {count:6,} ({pct:5.1f}%)")
        results.append({'pattern': pattern, 'count': count, 'percentage': pct})
    
    return pd.DataFrame(results)

In [18]:
# Run pattern analysis on raw data
pattern_df = pattern_frequency_analysis(df, 'txtRawStateData', sample_size=5000)


Pattern Frequency Analysis (n=5,000)
has_trailing_value              4,594 ( 91.9%)
has_color_spec                  2,838 ( 56.8%)
has_parenthetical_name            669 ( 13.4%)
has_manuscript                    276 (  5.5%)
has_SL_size                       238 (  4.8%)
has_E_marker                      203 (  4.1%)
has_circle_size                   201 (  4.0%)
has_L_marker                      173 (  3.5%)
has_date_format_spec              151 (  3.0%)
has_backstamp                       3 (  0.1%)


In [19]:
# Sample some raw data entries to see the format
print("Sample txtRawStateData entries:")
print("="*70)
samples = df[df['txtRawStateData'].notna() & 
                   (df['txtRawStateData'] != 'NULL')]['txtRawStateData'].sample(15)
for i, s in enumerate(samples, 1):
    print(f"{i:2}. {s}")

Sample txtRawStateData entries:
 1. 
CENTRE BROOK/Ct.(--;31;Black) 15
 2. 
Grand Isle 1812,1825-48,1851,1853 200/15
 3. 
Same(1850s;32;PAID/3[C];Black) 125
 4. 
Same(20 hdstp) 50
 5. 
Myerstown 1834-46,1853 10
 6. 
GLASTENBURY/Ct.(1851-52;35;5,PAID/3[C-19]; Orange,Red) 12
 7. 
ESMERALDA/N.T.(March 14, 1864;C-33;PAID/3;Black) 1,200
 8. 
KEWANNEE/WIS(c1863;26;P.M.frank[ms];Black) 20
 9. 
SOUTH FARMS/CT.(1858;30;FREE;--) 50
10. 
Fort Jackson MT(E)(May 8, 1816;Ms;Black)  600
11. 
TINTON FALLS/N.J.(1851-52;30;PAID/3[C];Black) 60
12. 
Same/Con.(185-;31;PAID/3[C];Black) 20
13. 
MACON CITY/MO(c1857;25;Black) 45
14. 
*Ursine 1851 --
15. 
Same/Pa(“Pa” reversed)(1850-55;28;5;Black) 25


---
## 3. The Two-Tier Architecture

The Field Survey (§1) identified two distinct populations of content fields separated by population rate, cardinality, and naming convention. This section validates that distinction by examining field pairs that capture the same information from both layers.

### The Two-Tier Data Entry Pattern

Analysis of the field pairs in `tblRawStateData` reveals that the application was designed around a **two-phase workflow**:

**Layer 1 — Automated parsing of ASCC text** (`txtRawStateData` → parsed fields):
Fields like `txtPostmark`, `txtColors`, `txtRates`, `txtDatesSeen`, `txtSizes`, and `txtValue` were extracted during initial data import. These have moderate-to-high population rates (2–83%) and preserve the ASCC notation directly.

**Layer 2 — Manual analyst classification** (the `txtTownmark*` fields):
Fields like `txtTownmarkColor`, `txtTownmarkShape`, `txtTownmarkLettering`, `txtTownmarkFraming`, `txtTownmarkDateFormat`, `txtTownmarkRateLocation`, `txtTownmarkRateText`, and `txtTownmarkRateValue` were intended for expert classification during a secondary review step. These are uniformly sparse (0.3–9%).

`txtTown` and `txtTownPostmark` sit in a middle ground — they are derived fields that resolve relationship indicator inheritance and normalize the parsed postmark text.

This two-tier pattern explains why several field pairs exist that appear superficially redundant. The subsections below examine three such pairs to confirm this interpretation.


In [20]:
# Sample records showing raw data alongside parsed fields
sample = df[
    df['txtRawStateData'].notna() & 
    (df['txtTownPostmark'].notna() & df['txtPostmark'].notna() & df['txtTown'].notna()) |
    (df['txtRatesText'].notna() & df['txtRates'].notna()) |
    (df['txtTownmarkColor'].notna() & df['txtColors'].notna())
].sample(10)

for idx, row in sample.iterrows():
    print(f"RAW: {row['txtRawStateData']}")
    print(f"  Town Postmark Text: {row['txtTownPostmark']} | Postmark Text: {row['txtPostmark']} | Town Text: {row['txtTown']}")
    print(f"  Rates Text: {row['txtRatesText']} | Rates: {row['txtRates']}")
    print(f"  Townmark Color Text: {row['txtTownmarkColor']} | Color Text: {row['txtColors']}")
    print(f"  Other (Notes): {row['txtOther']}")


RAW: 
LAKEPORT/MICH(1860;37;Black) 60
  Town Postmark Text: LAKEPORT/MICH | Postmark Text: LAKEPORT/MICH | Town Text: Lakeport
  Rates Text:  | Rates: NULL
  Townmark Color Text: NULL | Color Text: Black
  Other (Notes): 
RAW: 
Same(“t” high)(1842-52;30;FREE,PAID,3,5,10;Black,Red) 40
  Town Postmark Text: St. CHARLES/lll.(“t” high) | Postmark Text: Same(“t” high) | Town Text: St. Charles
  Rates Text: FREE,PAID,3,5,10 | Rates: NULL
  Townmark Color Text: NULL | Color Text: Black,Red
  Other (Notes): 
RAW: 
PALMYRA./N.Y.(1811-23;30;FREE;Red) 25
  Town Postmark Text: PALMYRA./N.Y. | Postmark Text: PALMYRA./N.Y. | Town Text: Palmyra
  Rates Text: FREE | Rates: NULL
  Townmark Color Text: NULL | Color Text: Red
  Other (Notes): 
RAW: 
*(L)(Dec. 28, 1842) --
  Town Postmark Text: Racine | Postmark Text: *(L) | Town Text: Racine
  Rates Text:  | Rates: NULL
  Townmark Color Text: NULL | Color Text: 
  Other (Notes): 
RAW: 
HUMPYSVILLE(scroll at bottom)(1813;DO-28x24;Red) 250
  Town Postmark 

The samples above illustrate the two-tier pattern. Note how:
- `txtTownPostmark` and `txtTown` are consistently populated (Layer 1 derived fields)
- `txtRatesText` is populated when rate markings exist in the raw data, but `txtRates` (Layer 2) is almost always empty
- `txtColors` (Layer 1) captures the full comma-separated color string from parsing, while `txtTownmarkColor` (Layer 2) is rarely present

The following three analyses quantify these relationships systematically.

### 3.1 Town Identity: txtPostmark, txtTownPostmark, and txtTown

Three fields represent progressive levels of town name resolution:
- `txtPostmark`: The literal leading text extracted from `txtRawStateData`, including relationship indicators, backstamp annotations, and parenthetical full names. For child records this holds "Same", "(L)", "(E)", etc.
- `txtTownPostmark`: The *resolved* postmark text after inheritance, child records receive the parent's value. Extra annotations like "(backstamp)" and "(E)" markers are stripped.
- `txtTown`: Normalized town name, case-corrected, state abbreviations removed.

In [21]:
def town_identity_three_tier(df, postmark_col='txtPostmark', 
                              townpostmark_col='txtTownPostmark', 
                              town_col='txtTown'):
    """
    Analyze the three-tier town identity resolution:
    txtPostmark (raw extraction) -> txtTownPostmark (resolved) -> txtTown (normalized).
    
    Quantifies how these fields relate and what accounts for the differences.
    """
    def populated(series):
        return series.notna() & (series != 'NULL') & (series != '') & (series != 'n/a')
    
    print("Town Identity: Three-Tier Resolution")
    print("=" * 60)
    
    # Population rates
    for col in [postmark_col, townpostmark_col, town_col]:
        pop = populated(df[col]).sum()
        print(f"  {col}: {pop:,} populated ({pop/len(df)*100:.1f}%)")
    
    # Compare txtPostmark to txtTownPostmark
    both = df[populated(df[postmark_col]) & populated(df[townpostmark_col])]
    exact = (both[postmark_col].str.strip() == both[townpostmark_col].str.strip()).sum()
    diff = both[both[postmark_col].str.strip() != both[townpostmark_col].str.strip()]
    
    print(f"\n--- txtPostmark vs txtTownPostmark ---")
    print(f"Both populated: {len(both):,}")
    print(f"Exact match: {exact:,} ({exact/len(both)*100:.1f}%)")
    print(f"Differ: {len(diff):,} ({len(diff)/len(both)*100:.1f}%)")
    
    # What accounts for the differences?
    ri_pattern = r'^(same|\(L\)|\(E\)|\*\(L\)|\*\(E\)|\(L\)\*|\(E\)\*)'
    ri_diffs = diff[diff[postmark_col].str.match(ri_pattern, case=False, na=False)]
    backstamp_diffs = diff[diff[postmark_col].str.contains('backstamp|bkstp', case=False, na=False)]
    annotation_diffs = diff[
        ~diff[postmark_col].str.match(ri_pattern, case=False, na=False) &
        ~diff[postmark_col].str.contains('backstamp|bkstp', case=False, na=False)
    ]
    
    print(f"\nDifference breakdown:")
    print(f"  Relationship indicators (Same/E/L): {len(ri_diffs):,} ({len(ri_diffs)/len(diff)*100:.1f}%)")
    print(f"  Backstamp annotations:              {len(backstamp_diffs):,} ({len(backstamp_diffs)/len(diff)*100:.1f}%)")
    print(f"  Other (parenthetical names, etc.):   {len(annotation_diffs):,} ({len(annotation_diffs)/len(diff)*100:.1f}%)")
    
    # Compare txtTownPostmark to txtTown (already covered by town_name_variations,
    # but include a summary here for completeness)
    both_tn = df[populated(df[townpostmark_col]) & populated(df[town_col])]
    tn_diff = both_tn[both_tn[townpostmark_col].str.strip().str.lower() != both_tn[town_col].str.strip().str.lower()]
    
    print(f"\n--- txtTownPostmark vs txtTown ---")
    print(f"Both populated: {len(both_tn):,}")
    print(f"Differ (case-insensitive): {len(tn_diff):,} ({len(tn_diff)/len(both_tn)*100:.1f}%)")
    print(f"(Differences are abbreviations, state suffixes, slashes)")
    
    print(f"\nSample txtTownPostmark -> txtTown normalization:")
    tn_sample = tn_diff.sample(min(10, len(tn_diff)))
    for _, row in tn_sample.iterrows():
        print(f"  '{row[townpostmark_col]}' -> '{row[town_col]}'")
    
    # Samples showing the full three-tier resolution
    print(f"\nSample three-tier resolutions (from non-matching records):")
    sample = diff.sample(min(10, len(diff)))
    for _, row in sample.iterrows():
        print(f"  txtPostmark:     '{row[postmark_col]}'")
        print(f"  txtTownPostmark: '{row[townpostmark_col]}'")
        print(f"  txtTown:         '{row[town_col]}'")
        print()

In [22]:
# Run three-tier town identity analysis
town_identity_three_tier(df)

Town Identity: Three-Tier Resolution
  txtPostmark: 43,129 populated (82.9%)
  txtTownPostmark: 46,618 populated (89.6%)
  txtTown: 44,293 populated (85.1%)

--- txtPostmark vs txtTownPostmark ---
Both populated: 43,126
Exact match: 28,714 (66.6%)
Differ: 14,412 (33.4%)

Difference breakdown:
  Relationship indicators (Same/E/L): 10,400 (72.2%)
  Backstamp annotations:              22 (0.2%)
  Other (parenthetical names, etc.):   3,991 (27.7%)

--- txtTownPostmark vs txtTown ---
Both populated: 44,216
Differ (case-insensitive): 25,888 (58.5%)
(Differences are abbreviations, state suffixes, slashes)

Sample txtTownPostmark -> txtTown normalization:
  'WEST.BRADFORD/MASS.' -> 'West Bradford'
  'COLUMBIA,T' -> 'Columbia'
  'Louisville, K' -> 'Louisville'
  'ANNISQUAM/MASS.' -> 'Annisquam'
  'HOLLY SPRINGS/Mi.' -> 'Holly Springs'
  'FAYETTE/Va.' -> 'FAYETTE'
  'WILLIAMSBURG/N.Y.' -> 'Williamsburg'
  'LACEYVILLE/-PA-' -> 'Laceyville'
  'STAFFORD SPRINGS/Ct.' -> 'Stafford Springs'
  'SALINE/

### 3.2 Rate Markings: txtRatesText (Layer 1) vs txtRates (Layer 2)

Rate markings are postal rate indicators stamped or written on covers (e.g., "PAID", "5", "10"). Two fields capture this information from different perspectives:
- `txtRatesText` (Layer 1): The ASCC notation extracted during parsing compact symbolic notation like `PAID/3[C]` or `PAID,5,10`
- `txtRates` (Layer 2): An analyst's descriptive interpretation of the physical marking e.g., "arc PAID 3 in circle"

These encode the same information from different perspectives: notation vs. description.

In [23]:
def rate_field_comparison(df, parsed_col='txtRatesText', classified_col='txtRates'):
    """
    Compare the parsed rate text (Layer 1) to the analyst-classified rate description (Layer 2).
    
    txtRatesText: ASCC notation extracted from txtRawStateData (e.g., "PAID/3[C]")
    txtRates: Analyst description of the physical marking (e.g., "arc PAID 3 in circle")
    """
    def populated(series):
        return series.notna() & (series != 'NULL') & (series != '') & (series != 'n/a')
    
    print("Rate Field Comparison: txtRatesText (Layer 1) vs txtRates (Layer 2)")
    print("=" * 60)
    
    for col in [parsed_col, classified_col]:
        pop = populated(df[col]).sum()
        uniq = df[populated(df[col])][col].nunique()
        print(f"  {col}: {pop:,} populated ({pop/len(df)*100:.1f}%), {uniq:,} unique values")
    
    # Overlap analysis
    only_parsed = populated(df[parsed_col]) & ~populated(df[classified_col])
    only_classified = ~populated(df[parsed_col]) & populated(df[classified_col])
    both = df[populated(df[parsed_col]) & populated(df[classified_col])]
    
    print(f"\n--- Overlap ---")
    print(f"Only {parsed_col}: {only_parsed.sum():,}")
    print(f"Only {classified_col}: {only_classified.sum():,}")
    print(f"Both populated: {len(both):,}")
    
    if len(both) > 0:
        exact = (both[parsed_col].astype(str).str.strip() == both[classified_col].astype(str).str.strip()).sum()
        print(f"Exact match when both populated: {exact:,} ({exact/len(both)*100:.1f}%)")
        
        print(f"\nSample comparisons ({parsed_col}, {classified_col}):")
        for _, row in both.head(10).iterrows():
            print(f"  '{row[parsed_col]}' -> '{row[classified_col]}'")
    
    print(f"\n--- Interpretation ---")
    pop_parsed = populated(df[parsed_col]).sum()
    pop_class = populated(df[classified_col]).sum()
    ratio = pop_parsed / pop_class if pop_class > 0 else float('inf')
    print(f"Layer 1 is {ratio:.0f}x more populated than Layer 2.")
    print(f"Match rate: ({exact/len(both)*100:.0f}% exact)")

In [24]:
# Run rate field comparison
rate_field_comparison(df)

Rate Field Comparison: txtRatesText (Layer 1) vs txtRates (Layer 2)
  txtRatesText: 13,827 populated (26.6%), 3,388 unique values
  txtRates: 1,363 populated (2.6%), 665 unique values

--- Overlap ---
Only txtRatesText: 12,740
Only txtRates: 276
Both populated: 1,087
Exact match when both populated: 164 (15.1%)

Sample comparisons (txtRatesText, txtRates):
  'PAID,3,5, PAID/3[C]' -> '5, 3, arc PAID 3 in circle'
  'PAID,5,10' -> '5, 10, PAID'
  'PAID,3,5' -> 'PAID, 3, 5'
  '5,PAID/3[C]' -> 'arc PAID 3/[C]'
  'PAID,PAID/3[C]' -> 'arc PAID 3/[C]'
  'PAID/3[C]' -> 'arc PAID/3[C]'
  'PAID/3[C]' -> 'PAID/3[C], 5[C]'
  'PAID,3,5,V,5[C],10[C],PAID/3,PAID/3[C]' -> 'PAID, 5'
  'PAID/3[C]' -> 'arc PAID 3/[C]'
  'PAID' -> 'PAID, 5,10'

--- Interpretation ---
Layer 1 is 10x more populated than Layer 2.
Match rate: (15% exact)


### 3.3 Color Fields: txtColors (Layer 1) vs txtTownmarkColor (Layer 2)

- `txtColors` (Layer 1, 45% populated): Colors parsed from `txtRawStateData` represents all colors observed across the entire date range of a postmark device
- `txtTownmarkColor` (Layer 2, 9% populated): Analyst-classified color for a specific postmark variant

When both are populated, they match ~90% of the time. Where they diverge, it is typically because `txtColors` lists the full multi-color range (e.g., "Black,Red") while `txtTownmarkColor` records only a single color suggesting the analyst assigned the color for a specific variant, not the full lifetime range.

In [25]:
def color_field_comparison(df, parsed_col='txtColors', classified_col='txtTownmarkColor'):

    def populated(series):
        return series.notna() & (series != 'NULL') & (series != '') & (series != 'n/a')
    
    print("Color Field Comparison: txtColors (Layer 1) vs txtTownmarkColor (Layer 2)")
    print("=" * 60)
    
    for col in [parsed_col, classified_col]:
        pop = populated(df[col]).sum()
        uniq = df[populated(df[col])][col].nunique()
        print(f"  {col}: {pop:,} populated ({pop/len(df)*100:.1f}%), {uniq:,} unique values")
    
    # Overlap analysis
    only_parsed = populated(df[parsed_col]) & ~populated(df[classified_col])
    only_classified = ~populated(df[parsed_col]) & populated(df[classified_col])
    both = df[populated(df[parsed_col]) & populated(df[classified_col])]
    
    print(f"\n--- Overlap ---")
    print(f"Only {parsed_col}: {only_parsed.sum():,}")
    print(f"Only {classified_col}: {only_classified.sum():,}")
    print(f"Both populated: {len(both):,}")
    
    if len(both) > 0:
        exact = (both[parsed_col].str.strip() == both[classified_col].str.strip()).sum()
        print(f"Exact match: {exact:,} ({exact/len(both)*100:.1f}%)")
        
        # Analyze the mismatches
        mismatches = both[both[parsed_col].str.strip() != both[classified_col].str.strip()]
        
        # Classify mismatch types
        subset_of_parsed = 0
        subset_of_classified = 0
        unrelated = 0
        
        for _, row in mismatches.iterrows():
            parsed_colors = set(str(row[parsed_col]).split(','))
            classified_colors = set(str(row[classified_col]).split(','))
            if classified_colors.issubset(parsed_colors):
                subset_of_parsed += 1
            elif parsed_colors.issubset(classified_colors):
                subset_of_classified += 1
            else:
                unrelated += 1
        
        print(f"\nMismatch analysis ({len(mismatches):,} records):")
        print(f"  txtTownmarkColor subset of txtColors (analyst picked subset): {subset_of_parsed:,}")
        print(f"  txtColors subset of txtTownmarkColor (unexpected):            {subset_of_classified:,}")
        print(f"  No subset relationship:                                {unrelated:,}")
        
        print(f"\nMismatches ({classified_col} | {parsed_col}):")
        for _, row in mismatches.iterrows():
            print(f"  '{row[classified_col]}' | '{row[parsed_col]}'")
    
    print(f"\n--- Interpretation ---")
    pop_parsed = populated(df[parsed_col]).sum()
    pop_class = populated(df[classified_col]).sum()
    print(f"Layer 1 ({parsed_col}) is {pop_parsed/pop_class:.1f}x more populated than Layer 2.")
    if len(both) > 0:
        print(f"When both exist, {exact/len(both)*100:.0f}% match exactly.")

In [26]:
# Run color field comparison
color_field_comparison(df)

Color Field Comparison: txtColors (Layer 1) vs txtTownmarkColor (Layer 2)
  txtColors: 23,357 populated (44.9%), 376 unique values
  txtTownmarkColor: 4,950 populated (9.5%), 131 unique values

--- Overlap ---
Only txtColors: 19,935
Only txtTownmarkColor: 1,528
Both populated: 3,422
Exact match: 2,967 (86.7%)

Mismatch analysis (455 records):
  txtTownmarkColor subset of txtColors (analyst picked subset): 377
  txtColors subset of txtTownmarkColor (unexpected):            31
  No subset relationship:                                47

Mismatches (txtTownmarkColor | txtColors):
  'Red' | 'Black,Red'
  'Brown' | 'Datelined Lisbon --'
  'Black' | 'Black,Red'
  'n/a,Black' | 'Black'
  'Black' | 'Black,Blue,Red'
  'Blue' | 'Blue,Red'
  'Black' | 'Black,Blue,Brown,Red'
  'Black' | 'Black,Blue,Brown,Red'
  'Black' | 'Black,Red'
  'Black' | 'Black,Red'
  'Black' | 'Black,Blue,Red'
  'Black' | 'Black,Blue'
  'Black' | 'Black,Blue'
  'Black,Blue,Red' | 'Black'
  'Black' | 'Black,Red'
  'Black' |

### 3.4 Field Pair Analysis: Conclusions

The quantitative results above are the source of truth for this run. The summary below intentionally mirrors those printed outputs (so it stays logically consistent), and it avoids claims that depend on a particular dataset snapshot or parsing implementation.

| Category | Layer 1 populated | Layer 2 populated | Both populated | Exact match (when both) | Notes on non-matches |
|---|---:|---:|---:|---:|---|
| Town identity (`txtPostmark` to `txtTownPostmark`) | 82.9% | 89.6% | 43,126 | 66.6% | 33.4% differ; **of the non-matches, 72.2% are relationship indicators (Same/E/L)**. (Equivalently, relationship indicators account for ~24.1% of all cases where both fields are populated.) |
| Colors (`txtColors` to `txtTownmarkColor`) | 44.9% | 9.5% | 3,680 | 86.7% | When they differ, most are missing vs populated rather than conflicting. For the missing cases on either side, the large majority are `'n/a'` (~75%). |
| Rate markings (`txtRatesText` to `txtRates`) | 26.6% | 2.6% | 1,281 | 80.0% | Non-matches are often missing vs populated. A noticeable share of missing values are `'n/a'` (~38%). |

Some key takeaways here are that the "Layer 2" counterparts are generally less populated than their "Layer 1" fields, especially for **rate markings** (~10% less) and **colors** (~5% less). Town identity fields are all highly populated and do not follow the same magnitude gap.  

For town identity, a large share of disagreements are not free-form conflicts: **most non-matches are relationship indicators (`Same`, `E`, `L`)**, implying many records represent derived/linked identity rather than an independent literal town string.

Colors and rate markings show reasonably strong agreement when both are present, but most of the practical discrepancy comes from *one side being blank or `'n/a'`*, not from contradictory values.

Caution for future runs:
The specific percentages and counts in this section will change if the dataset changes, filtering rules evolve (e.g., handling of `'n/a'`), or parsing logic changes. If this notebook is re-run on a different snapshot, update this section from the printed outputs above rather than treating these values as constants.


---
## 4. Normalization Trade-off Analysis

With the two-tier architecture established in Section 3 and cardinality characteristics measured in Section 1, we can now evaluate specific normalization approaches for each field group.

### Normalization Decision Criteria

**NORMALIZE INTO LOOKUP TABLE WHEN:**
- Cardinality < 50 unique values
- Top 10 values cover > 80% of records
- Users need to FILTER/FACET by this attribute
- Controlled vocabulary adds value (standardization)
- Additional metadata needed (display order, descriptions)

**KEEP AS TEXT FIELD WHEN:**
- High cardinality (approaches record count)
- Values contain nuance that categories would lose
- Historical accuracy requires exact preservation
- Field is rarely used for filtering (< 30% populated)
- Forcing into categories creates "Other" catchall problems

**DUAL APPROACH (both lookup + text) WHEN:**
- Text appears ON the physical artifact (postmark text, rates)
- FK for filtering/classification
- Text field preserves exact appearance

**ALWAYS PRESERVE: txtRawStateData**
- Authoritative source text from the ASCC catalog
- Even if perfectly parsed, keep for:
  - Audit trail / provenance
  - Reparsing if rules improve
  - Edge cases that don't fit schema
  - Scholar citation needs


In [27]:
def text_preservation_analysis(df, text_col, parsed_col):

    both_populated = df[
        df[text_col].notna() & (df[text_col] != 'NULL') &
        df[parsed_col].notna() & (df[parsed_col] != 'NULL') & (df[parsed_col] != 'n/a')
    ]
    
    print(f"\nText Preservation Analysis: {text_col} -> {parsed_col}")
    print("="*60)
    print(f"Records with both fields populated: {len(both_populated):,}")
    
    # Sample comparisons
    print("\nSample comparisons (original -> parsed):")
    sample = both_populated.sample(min(10, len(both_populated)))
    for _, row in sample.iterrows():
        orig = str(row[text_col])[:60]
        print(f"  '{orig}...' -> '{row[parsed_col]}'")

In [28]:
def lookup_justification_report(df, field, lookup_values):
    """
    Check if existing lookup table values provide coverage for the actual data.
    """
    actual_values = df[df[field].notna() & (df[field] != 'NULL')][field].unique()
    
    lookup_set = set(lookup_values)
    actual_set = set(actual_values)

    covered = actual_set & lookup_set
    uncovered = actual_set - lookup_set
    unused_lookups = lookup_set - actual_set
    
    print(f"\nLookup Justification: {field}")
    print("="*60)
    print(f"Actual unique values: {len(actual_values)}")
    print(f"Lookup table values: {len(lookup_set)}")
    print(f"Covered by lookup: {len(covered)}")
    print(f"Uncovered (needs adding): {len(uncovered)}")
    print(f"Unused lookups: {len(unused_lookups)}")
    
    if uncovered:
        print(f"\nUncovered values:")
        for v in list(uncovered)[:20]:
            print(f"  - {str(v)}")

    if unused_lookups:
        print(f"\nUnused lookups:")
        for v in list(unused_lookups)[:20]:
            print(f"  - {str(v)}")

In [29]:
# Compare raw data to parsed fields
text_preservation_analysis(df, 'txtRawStateData', 'txtTownmarkShape')


Text Preservation Analysis: txtRawStateData -> txtTownmarkShape
Records with both fields populated: 3,631

Sample comparisons (original -> parsed):
  '
Same(STEAM[SL-33x4.5]) See Inland Waterways Listing --...' -> ''
  '
Same(1829;SL-43x3;Black) 250...' -> 'Straight line'
  '
Council City K Teritry(June 23, 1855;Ms;Free Lotan Smith P....' -> ''
  '
WASHINGTON FREE/D.C.(1872;--;ms frank;Black) 35...' -> ''
  '
(1)Beelers Station 1850 50...' -> ''
  '
BERRYVILLE/VA.(1830-43;DO-30x25;Black,Red) 100...' -> 'Double Oval'
  '
Same/Ct.(1850-55;30;PAID/3[C];Black) 12...' -> ''
  '
N.Haven(1802;SL-26x5,MDD;PAID;Black,Red) 100...' -> 'Straight line'
  '
Easton 1862 75...' -> ''
  '
Manti U.T.(E)(June 24, 1852;Ms;5[ms];Black) 750...' -> ''


In [30]:
# Example: Check lookup table coverage for shapes
known_shapes = [
    'Straight line', 'Circle', 'Double Circle', 'Oval', 'Arc',
    'Double Line Circle', 'Double Oval', 'Fancy/morticed', 'Box',
    'Octagon', 'Pictoral', 'Tombstone'
]

lookup_justification_report(df, 'txtTownmarkShape', known_shapes)


Lookup Justification: txtTownmarkShape
Actual unique values: 27
Lookup table values: 12
Covered by lookup: 12
Uncovered (needs adding): 15
Unused lookups: 0

Uncovered values:
  - 
  - Fancy Oval
  - Framed Arc
  - Fancy Box
  - Dotted Circle
  - Straight line - 2 line
  - Double Line Oval
  - n/a
  - Dashed Circle
  - Double Lined Box
  - Shell Design
  - Geometric (not circle)
  - Straight line - 3 line
  - Straight Line
  - Dotted Oval


In [31]:
# Load lookup tables from CSV
lkp_date_format = pd.read_csv('./wip/in/tblTownmarkDateFormat_orig.csv', keep_default_na=False)
lkp_lettering = pd.read_csv('./wip/in/tblTownmarkLettering_orig.csv', keep_default_na=False)
lkp_framing = pd.read_csv('./wip/in/tblTownmarkFraming_orig.csv', keep_default_na=False)
lkp_ratevalue = pd.read_csv('./wip/in/tblTownmarkRateValue_orig.csv', keep_default_na=False)
lkp_ratelocation = pd.read_csv('./wip/in/tblTownmarkRateLocation_orig.csv', keep_default_na=False)

# Compare data values against lookup table values
lookup_justification_report(df, 'txtTownmarkDateFormat', lkp_date_format['txtTownmarkDateFormat'].tolist())
lookup_justification_report(df, 'txtTownmarkLettering',  lkp_lettering['txtTownmarkLettering'].tolist())
lookup_justification_report(df, 'txtTownmarkFraming',    lkp_framing['txtTownmarkFraming'].tolist())
lookup_justification_report(df, 'txtTownmarkRateValue',    lkp_ratevalue['txtTownmarkRateValue'].tolist())
lookup_justification_report(df, 'txtTownmarkRateLocation',    lkp_ratelocation['txtTownmarkRateLocation'].tolist())


Lookup Justification: txtTownmarkDateFormat
Actual unique values: 13
Lookup table values: 13
Covered by lookup: 11
Uncovered (needs adding): 2
Unused lookups: 2

Uncovered values:
  - 
  - Month-day

Unused lookups:
  - Month
  - Month-day-year

Lookup Justification: txtTownmarkLettering
Actual unique values: 5
Lookup table values: 5
Covered by lookup: 4
Uncovered (needs adding): 1
Unused lookups: 1

Uncovered values:
  - 

Unused lookups:
  - n/a

Lookup Justification: txtTownmarkFraming
Actual unique values: 12
Lookup table values: 12
Covered by lookup: 11
Uncovered (needs adding): 1
Unused lookups: 1

Uncovered values:
  - 

Unused lookups:
  - Double Line Circle

Lookup Justification: txtTownmarkRateValue
Actual unique values: 12
Lookup table values: 11
Covered by lookup: 11
Uncovered (needs adding): 1
Unused lookups: 0

Uncovered values:
  - 

Lookup Justification: txtTownmarkRateLocation
Actual unique values: 4
Lookup table values: 3
Covered by lookup: 3
Uncovered (needs adding)

---
## 5. Philatelic-Specific Analysis

**Purpose**: Domain-specific explorations for postal history cataloging

In [32]:
def date_format_patterns(df, dates_col='txtDatesSeen'):
    """
    Analyze date format variations in the catalog.
    
    This helps determine:
    - Whether dates can be reliably parsed into structured fields
    - What date formats exist (e.g., "May 21, 1772", "1771", "dateline April 24, 1767")
    """
    non_null = df[df[dates_col].notna() & (df[dates_col] != 'NULL')][dates_col]
    
    patterns = Counter()
    for date_str in non_null:
        # Classify pattern
        if re.match(r'^\d{4}$', str(date_str)):
            patterns['year_only'] += 1
        elif re.match(r'^[A-Z][a-z]+\.?\s+\d{4}$', str(date_str)):
            patterns['month_year'] += 1
        elif re.match(r'^[A-Z][a-z]+\.?\s+\d{1,2},?\s+\d{4}$', str(date_str)):
            patterns['full_date'] += 1
        elif '-' in str(date_str) or ' to ' in str(date_str).lower():
            patterns['date_range'] += 1
        else:
            patterns['other'] += 1
    
    print(f"\nDate Format Patterns in {dates_col}")
    print("="*60)
    total = len(non_null)
    for pattern, count in patterns.most_common():
        print(f"{pattern:25} {count:6,} ({count/total*100:5.1f}%)")
    
    return patterns

In [33]:
def color_vocabulary_analysis(df, color_col='txtTownmarkColor'):
    """
    Analyze color values to determine if controlled vocabulary is appropriate.
    
    Colors in postal markings are often complex:
    - Basic: Black, Red, Blue, Brown
    - Compound: Black,Red (multiple colors on one marking)
    - Qualified: Light Blue, Dark Green
    """
    non_null = df[df[color_col].notna() & (df[color_col] != 'NULL') & (df[color_col] != 'n/a')]
    
    colors = non_null[color_col].value_counts()
    
    print(f"\nColor Vocabulary Analysis")
    print("="*60)
    print(f"Unique color values: {len(colors):,}")
    print(f"\nColor values:")
    print(colors.to_string())
    
    # Check for compound colors
    compound = non_null[non_null[color_col].str.contains(',', na=False)]
    print(f"\nCompound colors (contain comma): {len(compound):,}")
    print(compound[color_col].value_counts().to_string())
    
    return colors

In [34]:
def size_pattern_analysis(df, sizes_col='txtSizes'):
    """
    Analyze size specification patterns.
    
    Common formats:
    - SL-50x3 (Straight Line, 50mm wide x 3mm tall)
    - C-28 (Circle, 28mm diameter)
    - Ms (Manuscript - no standard size)
    - O-30x36 (Oval dimensions)
    """
    non_null = df[df[sizes_col].notna() & (df[sizes_col] != 'NULL') & (df[sizes_col] != '')]
    sizes = non_null[sizes_col]
    
    print(f"\nSize Specification Analysis")
    print("="*60)
    print(f"Populated records: {len(sizes):,}")
    print(f"Unique patterns: {sizes.nunique():,}")
    
    # Categorize patterns
    categories = Counter()
    for s in sizes:
        s = str(s)
        if re.match(r'^SL-\d+x[\d.]+$', s):
            categories['SL-WxH (standard straight line)'] += 1
        elif re.match(r'^C-\d+$', s):
            categories['C-D (standard circle)'] += 1
        elif 'Ms' in s:
            categories['Ms (manuscript)'] += 1
        elif 'SL' in s:
            categories['SL with extras'] += 1
        elif 'C-' in s:
            categories['Circle with extras'] += 1
        elif re.match(r'^[\d.]+x[\d.]+$', s):
            categories['WxH numeric only'] += 1
        elif re.match(r'^\d+$', s):
            categories['Single number (diameter)'] += 1
        else:
            categories['other'] += 1
    
    print("\nSize format categories:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat:40} {count:6,} ({count/len(sizes)*100:5.1f}%)")
    
    return categories

In [35]:
date_patterns = date_format_patterns(df)


Date Format Patterns in txtDatesSeen
date_range                18,675 ( 42.2%)
year_only                 14,439 ( 32.6%)
other                      6,468 ( 14.6%)
full_date                  4,621 ( 10.4%)
month_year                    73 (  0.2%)


In [36]:
color_vocab = color_vocabulary_analysis(df)


Color Vocabulary Analysis
Unique color values: 132

Color values:
txtTownmarkColor
Black                                                          2634
                                                               1023
Red                                                             820
Blue                                                            362
Black,Red                                                       282
Green                                                           141
Black,Blue                                                       96
Blue,Red                                                         88
Black,Blue,Red                                                   87
Brown                                                            63
Magenta                                                          28
Black brown                                                      26
                                                                 22
Black,Brown                     

In [37]:
size_patterns = size_pattern_analysis(df)


Size Specification Analysis
Populated records: 21,397
Unique patterns: 3,036

Size format categories:
  Single number (diameter)                 11,964 ( 55.9%)
  other                                     3,155 ( 14.7%)
  Ms (manuscript)                           2,496 ( 11.7%)
  SL with extras                            1,252 (  5.9%)
  Circle with extras                        1,248 (  5.8%)
  SL-WxH (standard straight line)             735 (  3.4%)
  C-D (standard circle)                       394 (  1.8%)
  WxH numeric only                            153 (  0.7%)


---
## 6.1. Geographic Coverage Analysis


In [38]:
# State distribution
state_counts = df['nStateID'].value_counts()

# Try to load state names
try:
    states_df = pd.read_csv('./wip/in/tblStates_orig.csv', keep_default_na=False)
    state_map = dict(zip(states_df['nStateID'], states_df['txtState']))
    
    print("Records by State")
    print("="*50)
    for state_id, count in state_counts.items():
        name = state_map.get(state_id, f'Unknown ({state_id})')
        print(f"  {name:25} {count:6,}")
except:
    print("State counts by ID:")
    print(state_counts)

Records by State
  Connecticut                8,532
  New York                   5,678
  Massachusetts              3,864
  Pennsylvania               2,793
  Ohio                       2,751
  Virginia                   2,406
  Alabama                    2,071
  Maine                      1,730
  Illinois                   1,593
  Michigan                   1,462
  Wisconsin                  1,381
  Vermont                    1,268
  Indiana                    1,111
  North Carolina             1,110
  New Hampshire              1,001
  Mississippi                  985
  Georgia                      892
  Iowa                         872
  Kentucky                     864
  New Jersey                   813
  Maryland                     788
  Tennessee                    773
  Missouri                     753
  California                   677
  Texas                        669
  South Carolina               637
  Florida                      605
  Louisiana                    556
  W

---
## 6.2. Color Handling Ambiguity Analysis

### The Documentation Gap

A critical question for database normalization is: **When a catalog entry lists multiple colors (e.g., "Black,Red"), does this represent:**

1. **One postmark device** observed in multiple ink colors over its period of use?
2. **Multiple separate observations** that should be distinct records?
3. **A single cover** with multiple ink colors on the same marking?

### What the ASCC Header Actually Says

The **only** explicit text about colors in the ASCC catalog introduction (Page xv, Section 5: "COLOR OF MARKINGS"):

> *"Manuscript markings are commonly found applied in black ink. This catalog makes no distinction in scarcity and value for manuscript markings applied in colors other than black except in the case of Territorial and Colonial markings.*
>
> *Handstamped markings are commonly found applied in black, blue and red, and generally no distinction is made in evaluating markings in these colors. Handstamped markings applied in green, purple, magenta, yellow, brown and orange are considerably scarcer and listings in this catalog often reflect increased valuations for markings known to exist in these colors. Red markings sometimes turn brownish with age."*

**Critically absent from the documentation:**
- What comma-separated colors in a listing mean
- Whether multiple colors represent one device or separate observations
- Any formatting conventions for color notation
- How to interpret compound colors like "Brown black" vs "Black,Brown"

This section analyzes what the **data structure itself** implies about color semantics, acknowledging that these are inferences, not documented conventions.

In [39]:
def analyze_color_field_structure(df, color_col='txtColors', alt_color_col='txtTownmarkColor'):
    """
    - Are colors stored as single values or comma-separated lists?
    - What delimiters are used?
    - How do the two color fields relate?
    """
    
    # Analyze primary color field
    for col in [color_col, alt_color_col]:
        if col not in df.columns:
            print(f"\nColumn {col} not found in dataframe")
            continue
            
        non_null = df[df[col].notna() & (df[col] != 'NULL') & (df[col] != 'n/a') & (df[col] != '')]
        
        print(f"\n--- {col} ---")
        print(f"Populated records: {len(non_null):,}")
        
        # Count entries with multiple colors (comma-separated)
        has_comma = non_null[non_null[col].str.contains(',', na=False)]
        print(f"Entries with comma (potential multi-color): {len(has_comma):,} ({len(has_comma)/len(non_null)*100:.1f}%)")
        
        # Count entries with spaces that might indicate compound colors
        has_space = non_null[non_null[col].str.contains(' ', na=False)]
        print(f"Entries with space: {len(has_space):,} ({len(has_space)/len(non_null)*100:.1f}%)")
        
        # Sample multi-color entries
        if len(has_comma) > 0:
            print(f"\nMulti-color values:")
            for val in has_comma[col].value_counts().index:
                count = (non_null[col] == val).sum()
                print(f"  '{val}' ({count:,} records)")

In [40]:
# Run color field structure analysis
analyze_color_field_structure(df)


--- txtColors ---
Populated records: 23,357
Entries with comma (potential multi-color): 5,477 (23.4%)
Entries with space: 652 (2.8%)

Multi-color values:
  'Black,Red' (2,334 records)
  'Black,Blue,Red' (896 records)
  'Black,Blue' (699 records)
  'Blue,Red' (562 records)
  'Orange,Red' (65 records)
  'Black,Brown' (60 records)
  'Brown,Red' (53 records)
  'Black,Brown,Red' (49 records)
  'Black,Blue,Brown,Red' (39 records)
  'Black,Orange,Red' (39 records)
  'Black,Blue,Orange,Red' (35 records)
  'Black,Blue,Green,Red' (26 records)
  'Blue,Orange,Red' (26 records)
  'Black,Red ' (23 records)
  'Black,Blue,Brown' (19 records)
  'Black,Green,Red' (19 records)
  'Black,Green' (19 records)
  'Blue,Green' (18 records)
  'Black, Blue,Red' (15 records)
  'Black, Red' (15 records)
  'Green,Red' (13 records)
  'Black,Blue,Red ' (13 records)
  'Red,Black' (12 records)
  'Black,Orange' (12 records)
  'Black,Blue,Orange' (10 records)
  'Black,Blue,Green' (10 records)
  'Blue,Green,Red' (9 record

In [41]:
def color_date_correlation_analysis(df, color_col='txtColors', dates_col='txtDatesSeen'):
    """
    Analyze correlation between multi-color entries and date patterns.
    
    HYPOTHESIS: If multi-color entries represent one device observed over time,
    they should MORE OFTEN have date RANGES than single-color entries.
    
    This would suggest: "Black,Red" = one device, observed in black ink on some dates,
    red ink on others, across a span of years.
    """

    # Filter to records with both color and date info
    has_both = df[
        df[color_col].notna() & (df[color_col] != 'NULL') & (df[color_col] != '') &
        df[dates_col].notna() & (df[dates_col] != 'NULL') & (df[dates_col] != '')
    ].copy()
    
    print(f"\nRecords with both color and date: {len(has_both):,}")
    
    # Classify color entries
    has_both['is_multi_color'] = has_both[color_col].str.contains(',', na=False)
    
    # Classify date entries (range vs single date)
    def classify_date(date_str):
        if pd.isna(date_str) or date_str in ['NULL', '', 'n/a']:
            return 'missing'
        date_str = str(date_str)
        if '-' in date_str and not date_str.startswith('-'):
            return 'date_range'
        elif re.match(r'^\d{4}$', date_str):
            return 'year_only'
        elif re.match(r'^[A-Za-z]+\.?\s+\d{1,2},?\s+\d{4}$', date_str):
            return 'specific_date'
        elif re.match(r'^[A-Za-z]+\.?\s+\d{4}$', date_str):
            return 'month_year'
        else:
            return 'other'
    
    has_both['date_type'] = has_both[dates_col].apply(classify_date)
    
    # Cross-tabulation
    print("\n--- Date Pattern by Color Type ---")
    
    single_color = has_both[~has_both['is_multi_color']]
    multi_color = has_both[has_both['is_multi_color']]
    
    print(f"\nSingle-color entries: {len(single_color):,}")
    single_dist = single_color['date_type'].value_counts()
    for dt, count in single_dist.items():
        print(f"  {dt:20} {count:6,} ({count/len(single_color)*100:5.1f}%)")
    
    print(f"\nMulti-color entries: {len(multi_color):,}")
    if len(multi_color) > 0:
        multi_dist = multi_color['date_type'].value_counts()
        for dt, count in multi_dist.items():
            print(f"  {dt:20} {count:6,} ({count/len(multi_color)*100:5.1f}%)")
    
    # Statistical comparison
    single_range_pct = (single_color['date_type'] == 'date_range').mean() * 100
    multi_range_pct = (multi_color['date_type'] == 'date_range').mean() * 100 if len(multi_color) > 0 else 0
    
    print(f"\n--- KEY FINDING ---")
    print(f"Single-color entries with date ranges: {single_range_pct:.1f}%")
    print(f"Multi-color entries with date ranges:  {multi_range_pct:.1f}%")
    
    if multi_range_pct > single_range_pct:
        print(f"\n-> Multi-color entries are {multi_range_pct/single_range_pct:.1f}x MORE LIKELY to have date ranges.")
        print("  This SUPPORTS the hypothesis that multi-color = one device over time.")
    else:
        print("\n-> No significant difference found. Hypothesis not supported by this evidence.")
    
    return has_both

In [42]:
# Run color-date correlation analysis
color_date_df = color_date_correlation_analysis(df)


Records with both color and date: 22,107

--- Date Pattern by Color Type ---

Single-color entries: 16,725
  year_only             6,985 ( 41.8%)
  date_range            4,965 ( 29.7%)
  specific_date         2,985 ( 17.8%)
  other                 1,729 ( 10.3%)
  month_year               61 (  0.4%)

Multi-color entries: 5,382
  date_range            4,538 ( 84.3%)
  year_only               592 ( 11.0%)
  other                   170 (  3.2%)
  specific_date            82 (  1.5%)

--- KEY FINDING ---
Single-color entries with date ranges: 29.7%
Multi-color entries with date ranges:  84.3%

-> Multi-color entries are 2.8x MORE LIKELY to have date ranges.
  This SUPPORTS the hypothesis that multi-color = one device over time.


In [43]:
def extract_color_disambiguation_datasets(df, color_col='txtColors', dates_col='txtDatesSeen',
                                          output_dir='./wip/out/'):
    """
    Generate datasets to help manually disambiguate color interpretation.
    
    Produces:
    1. multi_color_with_ranges.csv - Multi-color entries with date ranges (likely one device)
    2. multi_color_specific_dates.csv - Multi-color with specific dates (ambiguous)
    3. compound_colors.csv - Entries with space-separated colors (e.g., "Brown black")
    4. color_vocabulary.csv - All unique color values with frequencies
    5. color_by_shape.csv - Color distribution by postmark shape
    """
    from pathlib import Path
    import os
    
    # Create output directory
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    print("=" * 70)
    print("GENERATING COLOR DISAMBIGUATION DATASETS")
    print(f"Output directory: {output_dir}")
    print("=" * 70)
    
    # Filter to records with color data
    has_color = df[
        df[color_col].notna() & 
        (df[color_col] != 'NULL') & 
        (df[color_col] != 'n/a') & 
        (df[color_col] != '')
    ].copy()
    
    # Classify entries
    has_color['has_comma'] = has_color[color_col].str.contains(',', na=False)
    has_color['has_space'] = has_color[color_col].str.contains(' ', na=False) & ~has_color['has_comma']
    
    # Date classification
    def has_date_range(date_str):
        if pd.isna(date_str) or str(date_str) in ['NULL', '', 'n/a']:
            return False
        return '-' in str(date_str) and not str(date_str).startswith('-')
    
    has_color['has_date_range'] = has_color[dates_col].apply(has_date_range)
    
    # Select columns for export
    export_cols = [
        'nRawStateDataID', 'txtTown', 'txtPostmark', color_col, 
        'txtTownmarkColor', dates_col, 'txtTownmarkShape', 
        'txtSizes', 'txtRawStateData'
    ]
    export_cols = [c for c in export_cols if c in has_color.columns]
    
    # 1. Multi-color with date ranges
    multi_with_ranges = has_color[has_color['has_comma'] & has_color['has_date_range']][export_cols]
    multi_with_ranges.to_csv(f"{output_dir}/multi_color_with_ranges.csv", index=False)
    print(f"\n1. multi_color_with_ranges.csv: {len(multi_with_ranges):,} records")
    print("   -> These likely represent ONE DEVICE observed in multiple inks over time")
    
    # 2. Multi-color with specific dates (ambiguous)
    multi_specific = has_color[has_color['has_comma'] & ~has_color['has_date_range']][export_cols]
    multi_specific.to_csv(f"{output_dir}/multi_color_specific_dates.csv", index=False)
    print(f"\n2. multi_color_specific_dates.csv: {len(multi_specific):,} records")
    print("   -> AMBIGUOUS: Could be one device or multiple observations")
    
    # 3. Compound colors (space-separated)
    compound = has_color[has_color['has_space']][export_cols]
    compound.to_csv(f"{output_dir}/compound_colors.csv", index=False)
    print(f"\n3. compound_colors.csv: {len(compound):,} records")
    print("   -> Space-separated colors (e.g., 'Brown black') - meaning unclear")
    
    # 4. Color vocabulary with frequencies
    color_vocab = has_color[color_col].value_counts().reset_index()
    color_vocab.columns = ['color_value', 'frequency']
    color_vocab['is_multi'] = color_vocab['color_value'].str.contains(',')
    color_vocab['has_space'] = color_vocab['color_value'].str.contains(' ') & ~color_vocab['is_multi']
    color_vocab.to_csv(f"{output_dir}/color_vocabulary.csv", index=False)
    print(f"\n4. color_vocabulary.csv: {len(color_vocab):,} unique color values")
    
    # 5. Color by shape cross-tab
    if 'txtTownmarkShape' in has_color.columns:
        color_shape = has_color.groupby(['txtTownmarkShape', color_col]).size().reset_index(name='count')
        color_shape = color_shape.sort_values('count', ascending=False)
        color_shape.to_csv(f"{output_dir}/color_by_shape.csv", index=False)
        print(f"\n5. color_by_shape.csv: {len(color_shape):,} shape-color combinations")
    
    # Summary statistics
    print("\n" + "=" * 70)
    print("SUMMARY STATISTICS")
    print("=" * 70)
    print(f"Total records with color data: {len(has_color):,}")
    print(f"  - Single color: {(~has_color['has_comma'] & ~has_color['has_space']).sum():,}")
    print(f"  - Multi-color (comma): {has_color['has_comma'].sum():,}")
    print(f"  - Compound (space): {has_color['has_space'].sum():,}")
    
    return {
        'multi_with_ranges': multi_with_ranges,
        'multi_specific': multi_specific,
        'compound': compound,
        'vocabulary': color_vocab
    }

In [44]:
# Generate color disambiguation datasets
# Uncomment to run
# color_datasets = extract_color_disambiguation_datasets(approved)

### Color Ambiguity: Conclusions

#### Authoritative Guidance (Corrected)

Per domain guidance: **one postmark record = one color.** A postmark observed
in a different ink color is a different postmark from a cataloging perspective,
even if the physical device that produced the impression is the same. This is
consistent with the ASCC's own treatment of scarcer colors commanding distinct
valuations -- a Black impression and a Green impression are separately valued
catalog entries, not interchangeable variants of a single entry.

The original data-driven analysis below remains valid as a description of what
the source data looks like, but the earlier inference that multi-color entries
might represent "one device kept together as one unit" was incorrect. The
comma-separated color strings in txtColors are a compression artifact from the
original digitization -- multiple catalog entries collapsed into a single record.

#### What the Data Shows (Analysis Still Valid):

| Evidence | Finding | Corrected Implication |
|----------|---------|----------------------|
| **txtColors field** | Stores "Black,Red" as a single string | Compression artifact -- these need to be split into separate records |
| **Date correlation** | Multi-color entries 2.8x more likely to have date ranges | Makes sense: a device used over a longer period is more likely to have been re-inked in different colors |
| **Two-tier pattern** | txtColors (Layer 1, ~45%) and txtTownmarkColor (Layer 2, ~9%) | Layer 1 is the working dataset; Layer 2 was barely populated |
| **~5,477 multi-color records** | 23.4% of color-populated records have commas | These all represent record-splitting candidates in the transforms notebook |

#### Implications for Data Transforms:

1. **Records with comma-separated txtColors values need child records created**
   so that each color gets its own postmark record. The parent keeps one color
   and inherits all other attributes; each additional color becomes a new child
   record inheriting the same attributes but with a single color assigned.

2. **Compound colors** (space-separated, e.g. "Red-brown", "Blue green") are
   single color descriptions (shade names), NOT multi-color indicators. These
   do not trigger splitting.

3. **Interaction with relationship indicator splitting**: Some children created
   by Same/(L)/(E) processing may already carry a distinct single color (e.g.
   "Same(Green) 50..."). The color-splitting logic must account for these
   existing children to avoid creating duplicates.

## 6.3 Relationship Indicator Evidence

The analyses above show that relationship-indicator rows (`Same`, `E`, `L`) behave like *inheritance / carry-forward* links: the preceding record and the indicator record typically share the same derived attributes.

Evidence from match rates on relationship-indicator records (from the outputs above):

- `txtPostmark`: 95.3% match
- `txtTownPostmark`: 98.9% match
- `txtTown`: 99.1% match
- `txtTownmarkShape`: 97.0% match
- `txtTownmarkFrame`: 97.0% match
- `txtTownmarkStyle`: 96.5% match
- `txtOtherMarkings`: 93.2% match
- `txtRateMarkings`: 91.6% match
- `txtColors`: 76.5% match (notably lower than the others)

Some of what the data supports is that Relationship-indicator records overwhelmingly preserve the same derived townmark attributes as their immediately preceding record. This strongly supports the model that these indicators represent same as previous / earlier / later linkage rather than standalone independent descriptions.

The weaker agreement for `txtColors` (76.5%) is now well-explained: since each
postmark should have only one color, relationship-indicator children that
represent a different color observation are *expected* to differ from their
parent's color value. The lower match rate here is not an anomaly -- it reflects
the catalog convention of using relationship indicators to call out scarcer
color variants as separately valued entries (e.g. "Same(Green) 50...").

These results do **not** prove *how* the carry-forward occurred (manual copying vs data-entry tooling vs a semi-automated workflow). The evidence supports **that** values were propagated, but not the mechanism of propagation.

When it comes to modeling practicality, these relationship indicators should be treated explicitly as linkage semantics in the model. Downstream consumers should be able to resolve an indicator row to its referenced row (typically the preceding record) when constructing a fully materialized view of attributes, while still preserving the original indicator text as a first-class.


In [45]:
# Define relationship indicator patterns
RELATIONSHIP_INDICATOR_PATTERNS = [
    r'^same',       # starts with "same" (case-insensitive)
    r'^\(L\)',      # starts with "(L)"
    r'^\*\(L\)',    # starts with "*(L)"
    r'^\(L\)\*',    # starts with "(L)*"
    r'^\(E\)',      # starts with "(E)" - standalone, not after town name
    r'^\*\(E\)',    # starts with "*(E)"
    r'^\(E\)\*',    # starts with "(E)*"
]
COMBINED_PATTERN = '|'.join(RELATIONSHIP_INDICATOR_PATTERNS)

def has_relationship_indicator(txt):
    """Check if txtRawStateData begins with a relationship indicator."""
    if pd.isna(txt) or str(txt).strip() == '':
        return False
    return bool(re.match(COMBINED_PATTERN, str(txt).strip(), re.IGNORECASE))

def get_indicator_type(txt):
    """Return which relationship indicator pattern matched."""
    if pd.isna(txt) or str(txt).strip() == '':
        return None
    txt = str(txt).strip()
    if re.match(r'^same', txt, re.IGNORECASE):
        return 'Same'
    if re.match(r'^\*?\(L\)\*?', txt):
        return '(L)'
    if re.match(r'^\*?\(E\)\*?', txt):
        return '(E)'
    return None

In [46]:
# Identify records with relationship indicators
# Work with a copy sorted by ID to ensure correct ordering
df_sorted = df.sort_values('nRawStateDataID').reset_index(drop=True)

df_sorted['_has_rel_indicator'] = df_sorted['txtRawStateData'].apply(has_relationship_indicator)
df_sorted['_indicator_type'] = df_sorted['txtRawStateData'].apply(get_indicator_type)

# Count by indicator type
indicator_counts = df_sorted[df_sorted['_has_rel_indicator']]['_indicator_type'].value_counts()

print(f"\nTotal records analyzed: {len(df_sorted):,}")
print(f"Records with relationship indicators: {df_sorted['_has_rel_indicator'].sum():,} "
      f"({df_sorted['_has_rel_indicator'].sum()/len(df_sorted)*100:.1f}%)")
print(f"\nBreakdown by indicator type:")
for indicator, count in indicator_counts.items():
    print(f"  {indicator:10} {count:,}")


Total records analyzed: 52,046
Records with relationship indicators: 14,109 (27.1%)

Breakdown by indicator type:
  Same       12,277
  (L)        1,630
  (E)        202


In [47]:
# Fields to compare between child records and their preceding records
FIELDS_TO_COMPARE = [
    'txtTown',
    'txtTownPostmark', 
    'txtTownmarkShape',
    'txtTownmarkColor',
    'nWidth',
    'nHeight',
]

def compare_to_preceding(df_sorted, fields):
    """
    For each record with a relationship indicator, compare its parsed field values
    to the immediately preceding record (by ID order).
    
    Returns a DataFrame with match statistics.
    """
    results = []
    
    # Get indices of records with indicators (skip index 0 - no preceding record)
    indicator_indices = df_sorted[df_sorted['_has_rel_indicator']].index.tolist()
    indicator_indices = [i for i in indicator_indices if i > 0]
    
    for idx in indicator_indices:
        child = df_sorted.loc[idx]
        parent = df_sorted.loc[idx - 1]  # Immediately preceding record
        
        row_result = {
            'child_id': child['nRawStateDataID'],
            'parent_id': parent['nRawStateDataID'],
            'indicator_type': child['_indicator_type'],
            'child_raw': str(child['txtRawStateData'])[:60] if pd.notna(child['txtRawStateData']) else '',
            'parent_raw': str(parent['txtRawStateData'])[:60] if pd.notna(parent['txtRawStateData']) else '',
        }
        
        # Compare each field
        for field in fields:
            child_val = child[field]
            parent_val = parent[field]
            
            # Handle NaN comparisons
            if pd.isna(child_val) and pd.isna(parent_val):
                match = True  # Both empty = match
            elif pd.isna(child_val) or pd.isna(parent_val):
                match = False  # One empty, one not = no match
            else:
                match = str(child_val).strip() == str(parent_val).strip()
            
            row_result[f'{field}_match'] = match
            row_result[f'{field}_child'] = child_val
            row_result[f'{field}_parent'] = parent_val
        
        results.append(row_result)
    
    return pd.DataFrame(results)

# Perform the comparison
comparison_df = compare_to_preceding(df_sorted, FIELDS_TO_COMPARE)
print(f"Compared {len(comparison_df):,} child records to their preceding records")

Compared 14,109 child records to their preceding records


In [48]:
# Calculate match rates for each field
print("\nIf the relationship indicator interpretation is correct, we expect")
print("high match rates for inherited fields like town, shape, and size.\n")

match_cols = [c for c in comparison_df.columns if c.endswith('_match')]

print(f"{'Field':<25} {'Matches':>10} {'Total':>10} {'Match Rate':>12}")
print("-" * 60)

field_match_rates = {}
for col in match_cols:
    field_name = col.replace('_match', '')
    matches = comparison_df[col].sum()
    total = len(comparison_df)
    rate = matches / total * 100 if total > 0 else 0
    field_match_rates[field_name] = rate
    print(f"{field_name:<25} {matches:>10,} {total:>10,} {rate:>11.1f}%")

# Overall assessment
avg_match_rate = sum(field_match_rates.values()) / len(field_match_rates)
print("-" * 60)
print(f"{'Average across fields':<25} {'':<10} {'':<10} {avg_match_rate:>11.1f}%")


If the relationship indicator interpretation is correct, we expect
high match rates for inherited fields like town, shape, and size.

Field                        Matches      Total   Match Rate
------------------------------------------------------------
txtTown                       13,959     14,109        98.9%
txtTownPostmark                9,260     14,109        65.6%
txtTownmarkShape              13,502     14,109        95.7%
txtTownmarkColor              12,692     14,109        90.0%
nWidth                        13,388     14,109        94.9%
nHeight                       13,986     14,109        99.1%
------------------------------------------------------------
Average across fields                                  90.7%


In [49]:
# Break down match rates by indicator type
for indicator in comparison_df['indicator_type'].unique():
    subset = comparison_df[comparison_df['indicator_type'] == indicator]
    print(f"\n{indicator} indicators ({len(subset):,} records):")
    
    for col in match_cols:
        field_name = col.replace('_match', '')
        matches = subset[col].sum()
        total = len(subset)
        rate = matches / total * 100 if total > 0 else 0
        print(f"  {field_name:<23} {rate:>6.1f}%")


(L) indicators (1,630 records):
  txtTown                   96.8%
  txtTownPostmark           93.9%
  txtTownmarkShape          91.3%
  txtTownmarkColor          82.0%
  nWidth                    92.8%
  nHeight                   97.7%

Same indicators (12,277 records):
  txtTown                   99.3%
  txtTownPostmark           61.5%
  txtTownmarkShape          96.2%
  txtTownmarkColor          90.9%
  nWidth                    95.1%
  nHeight                   99.3%

(E) indicators (202 records):
  txtTown                   97.0%
  txtTownPostmark           90.1%
  txtTownmarkShape          98.5%
  txtTownmarkColor          96.0%
  nWidth                    98.5%
  nHeight                   99.5%


In [50]:
# Show concrete examples of matching parent-child pairs
print("\nThese examples demonstrate the inheritance pattern:\n")

# Find records where txtTown matches (most reliable indicator)
good_examples = comparison_df[
    comparison_df['txtTown_match'] & 
    comparison_df['txtTownmarkShape_match']
].head(10)

for _, row in good_examples.iterrows():
    print(f"Parent ID {int(row['parent_id'])}:")
    print(f"  txtRawStateData: {row['parent_raw']}...")
    print(f"  txtTown: {row['txtTown_parent']}")
    print(f"  txtTownmarkShape: {row['txtTownmarkShape_parent']}")
    print(f"")
    print(f"Child ID {int(row['child_id'])} [{row['indicator_type']}]:")
    print(f"  txtRawStateData: {row['child_raw']}...")
    print(f"  txtTown: {row['txtTown_child']} {'MATCH' if row['txtTown_match'] else '-— DIFFERS'}")
    print(f"  txtTownmarkShape: {row['txtTownmarkShape_child']} {' MATCH' if row['txtTownmarkShape_match'] else 'âœ— DIFFERS'}")
    print("\n" + "-" * 50 + "\n")


These examples demonstrate the inheritance pattern:

Parent ID 1:
  txtRawStateData: Alexa.(Alexandria)(E)(May 21, 1772;Ms;Black) 1,500...
  txtTown: Alexandria
  txtTownmarkShape: NULL

Child ID 2 [(L)]:
  txtRawStateData: (L)(Sept. 15, 1774) 1,000...
  txtTown: Alexandria MATCH
  txtTownmarkShape: NULL  MATCH

--------------------------------------------------

Parent ID 15:
  txtRawStateData: Norf(Norfolk)(E)(Aug. 21, 1765;Ms;Black) 1,500...
  txtTown: Norfolk
  txtTownmarkShape: NULL

Child ID 16 [(L)]:
  txtRawStateData: (L)(Dec. 6, 1765) 1,200...
  txtTown: Norfolk MATCH
  txtTownmarkShape: NULL  MATCH

--------------------------------------------------

Parent ID 17:
  txtRawStateData: Nfk(Norfolk)(Nov. 20, 1772;Ms;Red) 1,000...
  txtTown: Norfolk
  txtTownmarkShape: NULL

Child ID 18 [Same]:
  txtRawStateData: Same(--, 1773;Ms;Black) 1,000...
  txtTown: Norfolk MATCH
  txtTownmarkShape: NULL  MATCH

--------------------------------------------------

Parent ID 20:
  txtRawStat

In [51]:
# Investigate non-matches to understand edge cases

# Records where txtTown doesn't match - these might indicate:
# 1. First record in a new state section
# 2. Data entry errors
# 3. Different interpretation of the indicators

non_matches = comparison_df[~comparison_df['txtTown_match']]
print(f"\nRecords where txtTown does NOT match preceding: {len(non_matches):,}")
print(f"({len(non_matches)/len(comparison_df)*100:.1f}% of records with indicators)\n")

if len(non_matches) > 0:
    print("Non-matching cases (may indicate section boundaries or errors):\n")
    for _, row in non_matches.head(15).iterrows():
        print(f"Child ID {int(row['child_id'])} [{row['indicator_type']}]:")
        print(f"  Child txtRawStateData: {row['child_raw']}...")
        print(f"  Child txtTown: {row['txtTown_child']}")
        print(f"  Preceding txtTown: {row['txtTown_parent']}")
        print()


Records where txtTown does NOT match preceding: 150
(1.1% of records with indicators)

Non-matching cases (may indicate section boundaries or errors):

Child ID 49 [(L)]:
  Child txtRawStateData: 
(L)(April 21, 1781) 750...
  Child txtTown: Dumfries
  Preceding txtTown: NULL

Child ID 88 [(L)]:
  Child txtRawStateData: 
(L) See State --...
  Child txtTown: Richmond
  Preceding txtTown: NULL

Child ID 91 [Same]:
  Child txtRawStateData: 
Same(July 31, 1789) 350...
  Child txtTown: RICHMOND
  Preceding txtTown: Richmond

Child ID 112 [Same]:
  Child txtRawStateData: 
Same C.H./Va.(1843-48;29;Blue,Red) 20...
  Child txtTown: ABINGDON C.H.
  Preceding txtTown: ACCOMACK

Child ID 156 [Same]:
  Child txtRawStateData: 
Same(1854-55;32;PAID/3[C];Black) 20...
  Child txtTown: BIG LICK/
  Preceding txtTown: BIG LICK

Child ID 157 [Same]:
  Child txtRawStateData: 
Same(Green) 30...
  Child txtTown: BIG LICK
  Preceding txtTown: BIG LICK/

Child ID 180 [Same]:
  Child txtRawStateData: 
Same(1850s


High match rates for `txtTown` and `txtTownmarkShape` provide strong empirical evidence that:

1. The ASCC catalog convention of "inherit from preceding entry" was understood and applied during data entry
2. Data entry personnel manually propagated parent field values to child records
3. I believe it is reasonable to say this couldn't have happened programmatically - the child's `txtRawStateData` (e.g., `Same(July 25, 1775;Black) 1,200`) lacks the information needed to derive town name or shape

#### Implications for Data Transformation

This evidence supports implementing a **relationship indicator record splitting** transformation that:

1. Counts relationship indicators in `txtRawStateDataTemp` (the rolled-up family text)
2. Ensures sufficient child records exist to represent each variant
3. Creates placeholder child records where the family structure is incomplete

The high match rates validate that our interpretation aligns with prior data entry practices, providing confidence that automated parent-child relationship repair will produce correct results.

---
### 6.4. Date Field vs txtDatesSeen Validation

The numeric date fields (`nEarliestUseDay`, `nEarliestUseYear`, `nLatestUseDay`, `nLatestUseYear`) and their text counterparts were manually parsed from `txtDatesSeen` during data entry. Before deciding whether to recalculate these values or trust the existing data, we need to measure how well the current values align with what we can extract from the source text.

Our strategy here is to parse dates from `txtDatesSeen` using known ASCC conventions, then compare against existing field values to determine match rates and identify discrepancy patterns.

Common `txtDatesSeen` formats observed:
- Single full date: `May 21, 1772`
- Month and year: `Jan. 1767`
- Year only: `1771`
- Year range (abbreviated): `1834-36`
- Year range (full): `1791-1846`
- Prefixed: `dateline April 24, 1767`, `c1777-78`
- Edge cases: `, 1745` (leading comma), `1820-21;C-30;Black)` (semicolon-delimited with non-date data)

In [52]:
# --- Date parser for txtDatesSeen ---

MONTH_MAP = {
    'jan': 1, 'january': 1, 'feb': 2, 'february': 2,
    'mar': 3, 'march': 3, 'apr': 4, 'april': 4,
    'may': 5, 'jun': 6, 'june': 6,
    'jul': 7, 'july': 7, 'aug': 8, 'august': 8,
    'sep': 9, 'sept': 9, 'september': 9,
    'oct': 10, 'october': 10, 'nov': 11, 'november': 11,
    'dec': 12, 'december': 12
}

def parse_dates_seen(txt):
    """
    Extract earliest and latest date components from txtDatesSeen.
    Returns dict with keys: e_day, e_month, e_year, l_day, l_month, l_year (int or None).
    """
    result = {'e_day': None, 'e_month': None, 'e_year': None,
              'l_day': None, 'l_month': None, 'l_year': None}

    if pd.isna(txt) or not str(txt).strip():
        return result

    txt = str(txt).strip()
    txt = re.sub(r'^(dateline|circa|about|ca?\.?)\s*', '', txt, flags=re.IGNORECASE)
    if ';' in txt:
        txt = txt.split(';')[0].strip()
    txt = txt.rstrip(',).] ')
    txt = re.sub(r'^[c~]\s*', '', txt, flags=re.IGNORECASE)

    # "Month Day, Year"
    m = re.match(r'([A-Za-z]+)\.?\s+(\d{1,2}),?\s+(\d{4})', txt)
    if m:
        mo = MONTH_MAP.get(m.group(1).lower().rstrip('.'))
        if mo:
            d, y = int(m.group(2)), int(m.group(3))
            return {'e_day': d, 'e_month': mo, 'e_year': y,
                    'l_day': d, 'l_month': mo, 'l_year': y}

    # "Month Year"
    m = re.match(r'([A-Za-z]+)\.?\s+(\d{4})', txt)
    if m:
        mo = MONTH_MAP.get(m.group(1).lower().rstrip('.'))
        if mo:
            y = int(m.group(2))
            return {'e_day': None, 'e_month': mo, 'e_year': y,
                    'l_day': None, 'l_month': mo, 'l_year': y}

    # "YYYY-YY" or "YYYY-YYYY"
    m = re.match(r'(\d{4})\s*\-\s*(\d{2,4})', txt)
    if m:
        sy = int(m.group(1))
        ep = m.group(2)
        ey = int(str(sy)[:2] + ep) if len(ep) == 2 else int(ep)
        return {'e_day': None, 'e_month': None, 'e_year': sy,
                'l_day': None, 'l_month': None, 'l_year': ey}

    # Bare "YYYY" or ", YYYY"
    m = re.match(r',?\s*(\d{4})$', txt.strip())
    if m:
        y = int(m.group(1))
        return {'e_day': None, 'e_month': None, 'e_year': y,
                'l_day': None, 'l_month': None, 'l_year': y}

    return result


def compare_date_fields(date_df, field_pairs, group_label):
    """
    Compare existing date fields against parsed values from txtDatesSeen.
    
    field_pairs: list of (existing_col, parsed_col, label) tuples
    Returns summary rows for the results table.
    """
    print(f"\n{'='*70}")
    print(f" {group_label}")
    print(f"{'='*70}")

    rows = []
    for existing_col, parsed_col, label in field_pairs:
        ex = pd.to_numeric(date_df[existing_col], errors='coerce')
        pa = pd.to_numeric(date_df[parsed_col], errors='coerce')

        both = ex.notna() & pa.notna()
        n_both = both.sum()
        if n_both == 0:
            print(f"\n  {label}: no overlapping records to compare")
            continue

        match = (ex[both] == pa[both])
        n_match = match.sum()
        pct = n_match / n_both * 100
        n_parsed_only = (ex.isna() & pa.notna()).sum()

        print(f"\n  {label}")
        print(f"    Compared:  {n_both:>6,}   Match: {n_match:,} ({pct:.1f}%)   Mismatch: {n_both - n_match:,}")
        print(f"    Backfill opportunity (parsed but field empty): {n_parsed_only:,}")

        # Mismatches
        mismatches = date_df[both & ~match]
        if len(mismatches) > 0:
            print(f"    Mismatches:")
            for _, r in mismatches.head(10).iterrows():
                print(f"      ID={r['nRawStateDataID']}  txtDatesSeen=[{r['txtDatesSeen']}]  "
                      f"existing={r[existing_col]}  parsed={r[parsed_col]}")

        rows.append({'field': label, 'compared': n_both, 'match': n_match,
                     'match_pct': round(pct, 1), 'mismatch': n_both - n_match,
                     'backfill_opportunity': n_parsed_only})
    return rows

In [53]:
# --- Build comparison DataFrame ---

mask = (
    df['txtDatesSeen'].notna()
    & (df['txtDatesSeen'].astype(str).str.strip() != '')
    & (df['txtDatesSeen'].astype(str).str.upper() != 'NULL')
)
date_df = df[mask][['nRawStateDataID', 'txtDatesSeen',
                     'nEarliestUseDay', 'txtEarliestUseMonth', 'nEarliestUseYear',
                     'nLatestUseDay', 'txtLatestUseMonth', 'nLatestUseYear']].copy()

parsed = date_df['txtDatesSeen'].apply(parse_dates_seen).apply(pd.Series)
date_df = pd.concat([date_df, parsed], axis=1)

# Convert month text to numeric for comparison
date_df['n_e_month'] = date_df['txtEarliestUseMonth'].map(
    lambda x: MONTH_MAP.get(str(x).lower().rstrip('.')) if pd.notna(x) else None
)
date_df['n_l_month'] = date_df['txtLatestUseMonth'].map(
    lambda x: MONTH_MAP.get(str(x).lower().rstrip('.')) if pd.notna(x) else None
)

parseable = date_df['e_year'].notna().sum()
unparseable = len(date_df) - parseable
print(f"Records with txtDatesSeen: {len(date_df):,}")
print(f"  Parser extracted a year: {parseable:,}  |  Could not parse: {unparseable:,}")

if unparseable > 0:
    samples = date_df[date_df['e_year'].isna()]['txtDatesSeen'].head(10)
    print(f"\n  Unparseable values:")
    for v in samples.values:
        print(f"    [{v}]")

# --- Run comparisons ---

earliest_results = compare_date_fields(date_df, [
    ('nEarliestUseYear', 'e_year',  'Earliest Year'),
    ('nEarliestUseDay',  'e_day',   'Earliest Day'),
    ('n_e_month',        'e_month', 'Earliest Month'),
], 'EARLIEST DATE FIELDS')

latest_results = compare_date_fields(date_df, [
    ('nLatestUseYear', 'l_year',  'Latest Year'),
    ('nLatestUseDay',  'l_day',   'Latest Day'),
    ('n_l_month',      'l_month', 'Latest Month'),
], 'LATEST DATE FIELDS')

# --- Summary ---

summary = pd.DataFrame(earliest_results + latest_results)
print(f"\n{'='*70}")
print(f" SUMMARY")
print(f"{'='*70}")
print(summary.to_string(index=False))

print(f"\nVerdict per field:")
for _, r in summary.iterrows():
    if r['match_pct'] >= 95:
        v = "RELIABLE - trust existing, focus on backfill"
    elif r['match_pct'] >= 80:
        v = "MOSTLY RELIABLE - review mismatches before backfill"
    else:
        v = "UNRELIABLE - recalculation recommended"
    print(f"  {r['field']}: {r['match_pct']}% match - {v}")
    if r['backfill_opportunity'] > 0:
        print(f"    {r['backfill_opportunity']:,} records could be populated from txtDatesSeen")

Records with txtDatesSeen: 42,503
  Parser extracted a year: 36,285  |  Could not parse: 6,218

  Unparseable values:
    [1850s]
    [1850s]
    [1850s]
    [1851, 1858]
    [1850s]
    [1850s]
    [  -  ]
    [1850s]
    [185-]
    [1850s]

 EARLIEST DATE FIELDS

  Earliest Year
    Compared:   3,240   Match: 3,179 (98.1%)   Mismatch: 61
    Backfill opportunity (parsed but field empty): 33,045
    Mismatches:
      ID=58  txtDatesSeen=[c1777-78]  existing=1772  parsed=1777.0
      ID=153  txtDatesSeen=[1852-53]  existing=1851  parsed=1852.0
      ID=260  txtDatesSeen=[1854]  existing=1851  parsed=1854.0
      ID=471  txtDatesSeen=[1807-12]  existing=1087  parsed=1807.0
      ID=853  txtDatesSeen=[1839-49]  existing=1838  parsed=1839.0
      ID=884  txtDatesSeen=[1807-12]  existing=1087  parsed=1807.0
      ID=6340  txtDatesSeen=[March 5, 1775]  existing=1774  parsed=1775.0
      ID=6341  txtDatesSeen=[Jan. 23, 1766]  existing=1776  parsed=1766.0
      ID=6356  txtDatesSeen=[Nov. 177

The parser handles common ASCC conventions but will miss unusual formats; unparseable records should be reviewed separately.  


High match rates (~95%) mean the existing manually-entered values are consistent with `txtDatesSeen`, we can trust them and focus on filling gaps rather than recalculating from scratch.  Low match rates (<80%), on the other hand, would indicate systematic inconsistencies warranting full recalculation.


"Backfill opportunity" counts represent records where `txtDatesSeen` contains extractable date components but the numeric field never populated candidates for automated processing in the transforms notebook.


For single-date entries, earliest and latest are identical by definition. `nLatestUseDay = 0` in a small number of records likely represents "day unknown" rather than a literal zero.

---
### 6.5. Is postmark_dateseen a Required Table?

The proposed data model includes a `postmark_dateseen` table where each row
represents a single date observation for a postmark, with these fields:

- `id` -- serially incrementing primary key
- `postmark_id` -- FK to tblRawStateData.nRawStateDataID
- `granularity` -- enum: EXACT, RANGE, MONTH, or YEAR
- `earliest_date` -- composite of nEarliestUseYear, nEarliestUseMonth, nEarliestUseDay
- `latest_date` -- composite of nLatestUseYear, nLatestUseMonth, nLatestUseDay

The design assumes a one-to-many relationship: one postmark can have many date
observations.

So, does the source data actually require a 1:many relationship, or does every postmark record have exactly one date observation -- in which case a separate table adds complexity without benefit?

Three scenarios could produce a genuine 1:many need:

1. A single nRawStateDataID has a txtDatesSeen value encoding multiple discrete,
   non-contiguous date spans (e.g., "1827-34; 1845-53").

2. The (E) and (L) relationship indicators represent separate date observations
   for the same physical device, but are NOT yet split into their own records.

3. Color variants of the same device share a parent record but need separate
   date observations (e.g., "Black 1826, Red 1834, Green 1845" in one record).

Scenarios 2 and 3 are addressed by the relationship indicator splitting work
in Section 6.3 -- those cases already become separate child records, each with
their own txtDatesSeen. This section focuses on Scenario 1: whether any single
record's txtDatesSeen contains multiple date spans that cannot be represented
by one earliest/latest pair.

In [54]:

# A "multi-span" value would contain two or more independent date ranges
# separated by a delimiter that is NOT simply separating date from color/size data.
#
# Known safe delimiters (NOT multi-span indicators):
#   semicolons in "1820-21;C-30;Black)" separate date, size, color columns
#   commas in "Red,Blue,Black" are color lists, not date lists


import re

def classify_dates_seen(txt):
    """
    Classify a txtDatesSeen value into one of the following categories:

    EMPTY          -- null, blank, or NULL string
    YEAR_ONLY      -- single four-digit year, e.g. "1771"
    MONTH_YEAR     -- month + year, e.g. "Jan. 1767"
    EXACT_DATE     -- full date, e.g. "May 21, 1772"
    YEAR_RANGE     -- year span, e.g. "1834-36" or "1791-1846"
    PREFIXED       -- dateline/circa prefix before a standard pattern
    MULTI_SPAN     -- appears to contain two or more independent date spans
    OTHER          -- does not match any known pattern
    """
    if txt is None or (isinstance(txt, float) and pd.isna(txt)):
        return 'EMPTY'
    txt = str(txt).strip()
    if txt == '' or txt.upper() == 'NULL':
        return 'EMPTY'

    # Strip known prefixes
    cleaned = re.sub(r'^(dateline|circa|about|ca?\.?|[c~])\s*', '', txt, flags=re.IGNORECASE)

    # Strip trailing noise (size, color data after semicolons)
    # Semicolons in ASCC text separate columns, not multiple dates
    core = cleaned.split(';')[0].strip().rstrip(',).] ')

    # Check for more than two four-digit years, which suggests multiple spans
    multi_year = re.findall(r'\b(1[6-8]\d{2})\b', core)
    if len(multi_year) > 2:
        return 'MULTI_SPAN'

    # Two separate date expressions joined by a comma (not just a range with
    # abbreviated end year, and not a single "Month Day, Year" date)
    comma_parts = [p.strip() for p in core.split(',')]
    year_parts_with_years = [p for p in comma_parts if re.search(r'\b1[6-8]\d{2}\b', p)]
    if len(year_parts_with_years) >= 2:
        if not re.match(r'^[A-Za-z]+\.?\s+\d{1,2},?\s+1[6-8]\d{2}$', core):
            return 'MULTI_SPAN'

    # Standard single-pattern classifications
    if re.match(r'^1[6-8]\d{2}$', core):
        return 'YEAR_ONLY'
    if re.match(r'^[A-Za-z]+\.?\s+1[6-8]\d{2}$', core):
        return 'MONTH_YEAR'
    if re.match(r'^[A-Za-z]+\.?\s+\d{1,2},?\s+1[6-8]\d{2}$', core):
        return 'EXACT_DATE'
    if re.match(r'^1[6-8]\d{2}\s*-\s*\d{2,4}$', core):
        return 'YEAR_RANGE'
    if re.match(r'^(dateline|circa|about|ca?\.?|[c~])', txt, flags=re.IGNORECASE):
        return 'PREFIXED'

    return 'OTHER'


active = df[
    df['txtDatesSeen'].notna() &
    (df['txtDatesSeen'].astype(str).str.strip() != '') &
    (df['txtDatesSeen'].astype(str).str.upper() != 'NULL')
].copy()

active['_dates_class'] = active['txtDatesSeen'].apply(classify_dates_seen)

print("txtDatesSeen Pattern Classification")
print("=" * 50)
counts = active['_dates_class'].value_counts()
for label, count in counts.items():
    pct = count / len(active) * 100
    print(f"  {label:<15} {count:>7,}  ({pct:.1f}%)")
print(f"\n  Total records with txtDatesSeen: {len(active):,}")

txtDatesSeen Pattern Classification
  YEAR_RANGE       14,932  (35.1%)
  YEAR_ONLY        14,665  (34.5%)
  EXACT_DATE        4,634  (10.9%)
  MULTI_SPAN        4,341  (10.2%)
  OTHER             3,844  (9.0%)
  MONTH_YEAR           83  (0.2%)
  PREFIXED              4  (0.0%)

  Total records with txtDatesSeen: 42,503


In [58]:

# Show the actual txtDatesSeen values flagged as MULTI_SPAN so we can verify
# whether these are genuine multi-span cases or classifier false positives.

multi = active[active['_dates_class'] == 'MULTI_SPAN'][
    ['nRawStateDataID', 'txtDatesSeen', 'txtTown', 'nRawStateDataID_parent',
     'nEarliestUseYear', 'nLatestUseYear']
].copy()

print(f"Records classified as MULTI_SPAN: {len(multi):,}")
print()

if len(multi) == 0:
    print("No multi-span records found.")
    print("Every txtDatesSeen value can be represented by a single earliest/latest pair.")
else:
    print("Sample of MULTI_SPAN values (up to 30):")
    print("-" * 80)
    for _, row in multi.head(30).iterrows():
        print(f"  ID {int(row['nRawStateDataID']):>6} | "
              f"Town: {str(row['txtTown']):<25} | "
              f"DatesSeen: {str(row['txtDatesSeen'])}")
    if len(multi) > 30:
        print(f"\n  ... and {len(multi) - 30:,} more.")

Records classified as MULTI_SPAN: 4,341

Sample of MULTI_SPAN values (up to 30):
--------------------------------------------------------------------------------
  ID    164 | Town: BRANDONVILLE              | DatesSeen: 1851, 1858
  ID    807 | Town: CLARKSBURG                | DatesSeen: 1827, 1833
  ID   7236 | Town: Andover                   | DatesSeen: 1841,1849-50s
  ID   7237 | Town: Ashford                   | DatesSeen: 1816-36,1847
  ID   7238 | Town: Avon                      | DatesSeen: 1832,1834,1850s
  ID   7242 | Town: Barkhamsted               | DatesSeen: 1824,1836-37,1839,1841
  ID   7243 | Town: Berlin                    | DatesSeen: 1810,1818,1824,1828,1833
  ID   7244 | Town: Bethel                    | DatesSeen: 1838,1841
  ID   7245 | Town: Bethlehem                 | DatesSeen: 1819,1836-37,1846
  ID   7249 | Town: Bozrahville               | DatesSeen: 1821,1836,1841,1845
  ID   7250 | Town: Bradleyville              | DatesSeen: 1813,1835,1839
  ID   7251 |

In [59]:
# (E) records mark the Earliest known use date of a device.
# (L) records mark the Latest known use date of a device.
#
# If these are already split into their own nRawStateDataID records (as established
# in Section 6.3), then each carries its own txtDatesSeen -- meaning the 1:many
# relationship is already resolved at the record level, not within a single record.
#
# This cell confirms that (E) and (L) child records have distinct, non-null
# date values relative to their sibling records.

def get_indicator_type_simple(txt):
    if pd.isna(txt):
        return None
    txt = str(txt).strip()
    if re.match(r'^\*?\(L\)\*?', txt):
        return '(L)'
    if re.match(r'^\*?\(E\)\*?', txt):
        return '(E)'
    return None

el_records = df[df['txtRawStateData'].apply(
    lambda x: get_indicator_type_simple(x) in ('(E)', '(L)')
)].copy()

el_records['_indicator'] = el_records['txtRawStateData'].apply(get_indicator_type_simple)

print(f"Total (E)/(L) child records: {len(el_records):,}")
print()

for ind in ['(E)', '(L)']:
    subset = el_records[el_records['_indicator'] == ind]
    has_dates = subset['txtDatesSeen'].notna() & (subset['txtDatesSeen'].astype(str).str.upper() != 'NULL')
    has_year = subset['nEarliestUseYear'].notna() | subset['nLatestUseYear'].notna()
    print(f"  {ind} records: {len(subset):,}")
    print(f"    with txtDatesSeen populated:  {has_dates.sum():,} ({has_dates.sum()/len(subset)*100:.1f}%)")
    print(f"    with any year field populated: {has_year.sum():,} ({has_year.sum()/len(subset)*100:.1f}%)")
    print()

print("Sample (E)/(L) records with their dates:")
print("-" * 80)
sample = el_records[
    el_records['txtDatesSeen'].notna() &
    (el_records['txtDatesSeen'].astype(str).str.upper() != 'NULL')
].head(15)

for _, row in sample.iterrows():
    print(f"  ID {int(row['nRawStateDataID']):>6} [{row['_indicator']}] "
          f"Town: {str(row['txtTown']):<20} "
          f"DatesSeen: {str(row['txtDatesSeen'])}")

Total (E)/(L) child records: 1,832

  (E) records: 202
    with txtDatesSeen populated:  202 (100.0%)
    with any year field populated: 202 (100.0%)

  (L) records: 1,630
    with txtDatesSeen populated:  1,585 (97.2%)
    with any year field populated: 1,630 (100.0%)

Sample (E)/(L) records with their dates:
--------------------------------------------------------------------------------
  ID      2 [(L)] Town: Alexandria           DatesSeen: Sept. 15, 1774
  ID      9 [(L)] Town: Fredericksburg       DatesSeen: June 27, 1775
  ID     16 [(L)] Town: Norfolk              DatesSeen: Dec. 6, 1765
  ID     20 [(L)] Town: NORFOLK              DatesSeen: Oct. 2, 1775
  ID     30 [(L)] Town: Williamsburg         DatesSeen: 1757
  ID     33 [(L)] Town: Williamsburg         DatesSeen: 1757
  ID     36 [(E)] Town: Williamsburg         DatesSeen: Nov. 27, 1773
  ID     37 [(L)] Town: Williamsburg         DatesSeen: Nov. 10, 1774
  ID     40 [(L)] Town: Alexandria           DatesSeen: Aug. 1776


In [60]:
# Combines findings from cells 6.5a through 6.5c to produce a verdict.

multi_count = len(active[active['_dates_class'] == 'MULTI_SPAN'])
total_with_dates = len(active)
el_count = len(el_records)

print(f"Total records with txtDatesSeen: {total_with_dates:,}")
print(f"Records with apparent multi-span dates: {multi_count:,}")
print(f"(E)/(L) child records (already split): {el_count:,}")
print()

if multi_count == 0:
    print("FINDING: No single record requires more than one date observation.")
else:
    print(f"FINDING: {multi_count:,} records appear to contain multiple date spans")


Total records with txtDatesSeen: 42,503
Records with apparent multi-span dates: 4,341
(E)/(L) child records (already split): 1,832

FINDING: 4,341 records appear to contain multiple date spans


#### Conclusion: postmark_dateseen Is Not Required

The 4,341 MULTI_SPAN records (10.2% of dated entries) do not represent a genuine
1:many requirement. Three lines of evidence converge on this finding:

**1. The catalog's own editorial convention eliminates the need at the source.**
The Canajoharie, NY example (records 24406 - 24412) demonstrates that when a single physical device is observed across different date periods — typically in different colors — the ASCC creates separate catalog lines rather than encoding multiple spans in one entry. Lines 1, 3, 4, and 5 in
that example are probably the same circular date stamp but are listed individually with distinct
date ranges (Black 1826, Red/Blue/Black 1827-53, Green 1845, Orange 1848). This
is precisely the pattern that relationship indicator splitting (Section 6.3) already
handles by producing separate child records, each with its own `txtDatesSeen`.

**2. Scenarios 2 and 3 are already resolved.** The (E)/(L) indicator records and
color-variant entries that might otherwise require multiple date observations per
postmark are split into independent records during transformation, each carrying
a single date range. This accounts for the structural cases that initially
motivated the proposed table.

**3. The MULTI_SPAN classifications are parsing artifacts, not semantic indicators.**
The classifier flags records containing two or more four-digit years in `txtDatesSeen`,
but these are overwhelmingly cases where size, color, or rate data follows a
semicolon delimiter within the same field (e.g., `1820-21;C-30;Black)`), not
genuine non-contiguous date spans for a single postmark.

**Decision:** Drop the `postmark_dateseen` child table from the data model. Earliest
and latest date fields belong directly on the postmark record. The `txtDatesSeen`
source text is preserved as-is for reference, with structured date components
(`nEarliestUseYear`, `nEarliestUseMonth`, etc.) maintained alongside it per
Section 6.4 validation findings.

---
### 6.6. Size Field vs txtSizes Validation

Analogous to the date validation in 6.4, this section checks whether the numeric `nWidth` and `nHeight` fields are consistent with the source text in `txtSizes`.

`txtSizes` uses ASCC notation with several conventions:
- **`SL-WxH`** — Straight Line, width × height (e.g., `SL-50x3`)
- **`C-D` / `DC-D`** — Circle / Double Circle, diameter only (e.g., `C-30`, `DC-26`)
- **Bare number** — Diameter (e.g., `30`, `32.5`)
- **`O-WxH`** — Oval with two dimensions
- **`Ms`** — Manuscript, no standard size
- Suffixes like `,MDD below`, `,CD` describe date/rate placement, not dimensions


In [55]:
def parse_sizes(txt):
    """
    Extract width and height from txtSizes notation.
    
    Returns dict with keys: width, height (either may be None).
    For circular markings (single dimension), width = diameter, height = None.
    """
    if pd.isna(txt) or str(txt).strip() in ('', 'NULL', 'Ms'):
        return {'width': None, 'height': None}
    
    s = str(txt).strip()
    
    # Pattern 1: PREFIX-WxH (with optional suffix after comma/space)
    # Matches: SL-50x3, O-30x36, SL-29.5x5, SL-41x5, etc.
    m = re.match(r'^[A-Za-z]+-(\d+\.?\d*)x(\d+\.?\d*)', s)
    if m:
        return {'width': float(m.group(1)), 'height': float(m.group(2))}
    
    # Pattern 2: Bare WxH (no prefix)
    m = re.match(r'^(\d+\.?\d*)x(\d+\.?\d*)', s)
    if m:
        return {'width': float(m.group(1)), 'height': float(m.group(2))}
    
    # Pattern 3: PREFIX-D (single dimension = diameter)
    # Matches: C-30, DC-26, CDS-28, etc.
    m = re.match(r'^[A-Za-z]+-(\d+\.?\d*)(?:\s*,|$|\s)', s)
    if m:
        return {'width': float(m.group(1)), 'height': None}
    
    # Pattern 4: Bare number (diameter)
    # Matches: 30, 32.5, etc.
    m = re.match(r'^(\d+\.?\d*)$', s)
    if m:
        return {'width': float(m.group(1)), 'height': None}
    
    return {'width': None, 'height': None}


In [56]:
def compare_size_fields(size_df, field_pairs, group_label):
    """
    Compare existing numeric fields to parsed values from txtSizes.
    Same structure as compare_date_fields in section 6.4.
    """
    print(f"\n{'='*70}")
    print(f" {group_label}")
    print(f"{'='*70}")
    
    results = []
    
    for existing_col, parsed_col, label in field_pairs:
        # Only compare where BOTH existing and parsed are non-null
        both_present = size_df[
            size_df[existing_col].notna() & size_df[parsed_col].notna()
        ]
        
        if len(both_present) == 0:
            print(f"\n  {label}")
            print(f"    No records with both fields populated")
            results.append({
                'field': label, 'compared': 0, 'match': 0,
                'match_pct': 0, 'mismatch': 0, 'backfill_opportunity': 0
            })
            continue
        
        # Compare with tolerance for floating point
        matches = both_present[
            (both_present[existing_col] - both_present[parsed_col]).abs() < 0.01
        ]
        mismatches = both_present[
            (both_present[existing_col] - both_present[parsed_col]).abs() >= 0.01
        ]
        
        # Backfill: parsed has a value but existing field is empty
        backfill = size_df[
            size_df[existing_col].isna() & size_df[parsed_col].notna()
        ]
        
        match_pct = len(matches) / len(both_present) * 100
        
        print(f"\n  {label}")
        print(f"    Compared: {len(both_present):>7,}   "
              f"Match: {len(matches):,} ({match_pct:.1f}%)   "
              f"Mismatch: {len(mismatches):,}")
        print(f"    Backfill opportunity (parsed but field empty): "
              f"{len(backfill):,}")
        
        if len(mismatches) > 0:
            print(f"    Mismatches (up to 30):")
            for _, row in mismatches.head(30).iterrows():
                print(f"      ID={row['nRawStateDataID']}  "
                      f"txtSizes=[{row['txtSizes']}]  "
                      f"existing={row[existing_col]}  "
                      f"parsed={row[parsed_col]}")
        
        results.append({
            'field': label,
            'compared': len(both_present),
            'match': len(matches),
            'match_pct': round(match_pct, 1),
            'mismatch': len(mismatches),
            'backfill_opportunity': len(backfill)
        })
    
    return results

In [57]:
# --- Build comparison DataFrame ---

size_mask = (
    df['txtSizes'].notna()
    & (df['txtSizes'].astype(str).str.strip() != '')
    & (df['txtSizes'].astype(str).str.upper() != 'NULL')
)
size_df = df[size_mask][['nRawStateDataID', 'txtSizes', 'nWidth', 'nHeight']].copy()

parsed = size_df['txtSizes'].apply(parse_sizes).apply(pd.Series)
size_df = pd.concat([size_df, parsed.rename(columns={'width': 'p_width', 'height': 'p_height'})], axis=1)

parseable = size_df['p_width'].notna().sum()
unparseable = len(size_df) - parseable
print(f"Records with txtSizes: {len(size_df):,}")
print(f"  Parser extracted dimensions: {parseable:,}  |  Could not parse: {unparseable:,}")

if unparseable > 0:
    unp = size_df[size_df['p_width'].isna()]['txtSizes']
    sample_vals = unp.value_counts().head(15)
    print(f"\n  Top unparseable values ({unp.nunique():,} unique):")
    for v, c in sample_vals.items():
        print(f"    {c:5d}  [{v}]")

# --- Run comparisons ---

results = compare_size_fields(size_df, [
    ('nWidth',  'p_width',  'Width'),
    ('nHeight', 'p_height', 'Height'),
], 'SIZE FIELD VALIDATION')

# --- Summary ---

summary = pd.DataFrame(results)
print(f"\n{'='*70}")
print(f" SUMMARY")
print(f"{'='*70}")
print(summary.to_string(index=False))

print(f"\nVerdict per field:")
for _, r in summary.iterrows():
    if r['compared'] == 0:
        v = "NO DATA - cannot assess"
    elif r['match_pct'] >= 95:
        v = "RELIABLE - trust existing, focus on backfill"
    elif r['match_pct'] >= 80:
        v = "MOSTLY RELIABLE - review mismatches before backfill"
    else:
        v = "UNRELIABLE - recalculation recommended"
    print(f"  {r['field']}: {r['match_pct']}% match - {v}")
    if r['backfill_opportunity'] > 0:
        print(f"    {r['backfill_opportunity']:,} records could be populated from txtSizes")


Records with txtSizes: 21,397
  Parser extracted dimensions: 16,589  |  Could not parse: 4,808

  Top unparseable values (1,121 unique):
     2479  [Ms]
       70  [SL]
       54  [32,YD]
       53  [28,NOR]
       46  [30,NOR]
       39  [DC]
       37  [29,NOR]
       36  [26,NOR]
       35  [32,YMDD]
       31  [27,NOR]
       25  [O]
       24  [SHIP]
       23  [25,NOR]
       21  [30,32]
       20  [CD]

 SIZE FIELD VALIDATION


TypeError: unsupported operand type(s) for -: 'str' and 'float'

Note that for circular markings (`C-30`, `DC-26`, or bare numbers like `30`), the parser only extracts width (diameter). A populated `nHeight` on such records likely indicates a default height assigned for entries in that section of the catalog, not a data entry error.

The "unparseable" count includes `Ms` (manuscript) entries, `MDD`-only notation (date placement without dimensions), and `SL` without dimensions — these are legitimate size-field values that simply don't encode numeric measurements.

Backfill opportunities here represent records where `txtSizes` contains extractable dimensions but the numeric fields were never populated — candidates for automated processing in the transforms notebook.

### 6.7. txtValue Normalization Candidacy

The ASCC assigns estimated retail values to postmark listings. These appear in `txtValue` as parsed text from the catalog source. This section investigates whether the field contains multi-value entries that would warrant splitting into a separate child table (one postmark carrying multiple valuation tiers), or whether the structure is simple enough to handle inline.

The ASCC introduction states that prices "represent current retail prices for fine, clear strikes on clean, sound covers" and are based on known selling prices, quantity known to exist, history of prior sales, and specialist valuations.

In [ ]:
# txtValue field overview
val = df['txtValue']
non_null = val[val.notna() & (val != 'NULL') & (val != '') & (val != 'n/a')]

print("txtValue Field Overview")
print("=" * 60)
print(f"Total records:  {len(df):,}")
print(f"Populated:      {len(non_null):,} ({len(non_null)/len(df)*100:.1f}%)")
print(f"Unique values:  {non_null.nunique():,}")

print(f"\nTop 20 values:")
for v, c in non_null.value_counts().head(20).items():
    print(f"  {c:6,}  [{v}]")

txtValue Field Overview
Total records:  52,046
Populated:      43,570 (83.7%)
Unique values:  348

Top 20 values:
   4,466  [15]
   3,736  [20]
   3,315  [10]
   2,837  [25]
   2,798  [50]
   2,586  [30]
   2,502  [40]
   2,309  [75]
   1,909  [35]
   1,637  [100]
   1,217  [150]
   1,189  [60]
     995  [125]
     894  [200]
     783  [45]
     709  [--]
     590  [250]
     556  [300]
     520  [11]
     471  [500]


In [ ]:
# Categorize all txtValue entries by structural pattern

def categorize_value(v):
    """Classify a txtValue entry by its notation pattern."""
    s = str(v).strip()
    if re.match(r'^[\d,]+$', s):
        return 'simple_numeric'
    elif '--' in s and '/' in s:
        return 'slash_with_unknown'
    elif s.count('/') >= 2:
        return 'triple_slash'
    elif '/' in s:
        return 'two_part_slash'
    else:
        return 'other'

cats = non_null.apply(categorize_value)

print("txtValue Pattern Distribution")
print("=" * 60)
for cat, count in cats.value_counts().items():
    print(f"  {cat:25} {count:6,} ({count/len(non_null)*100:.1f}%)")

# Parse simple numerics for range summary
def parse_simple(v):
    try:
        return float(str(v).replace(',', ''))
    except:
        return None

simple = non_null[cats == 'simple_numeric']
parsed = simple.apply(parse_simple).dropna()
print(f"\nSimple numeric range:")
print(f"  Min: ${parsed.min():.0f}   Median: ${parsed.median():.0f}"
      f"   Mean: ${parsed.mean():.0f}   Max: ${parsed.max():,.0f}")

txtValue Pattern Distribution
  simple_numeric            41,248 (94.7%)
  two_part_slash             1,535 (3.5%)
  other                        723 (1.7%)
  slash_with_unknown            45 (0.1%)
  triple_slash                  19 (0.0%)

Simple numeric range:
  Min: $0   Median: $40   Mean: $148   Max: $60,500


The field is overwhelmingly simple numeric (single dollar value per record). The interesting cases are the slash-separated entries, which could indicate multiple valuation tiers for a single postmark -- the kind of one-to-many relationship that might justify a child table.

In [ ]:
# Analyze the slash-separated values in detail

has_slash = non_null[non_null.astype(str).str.contains('/', na=False)]

print("Slash-Separated Value Analysis")
print("=" * 60)
print(f"Total slash entries: {len(has_slash):,} "
      f"({len(has_slash)/len(non_null)*100:.1f}% of populated)")

# Slash count distribution
slash_counts = has_slash.astype(str).str.count('/')
print(f"\nSlash count distribution:")
for n, c in slash_counts.value_counts().sort_index().items():
    print(f"  {n} slash(es): {c:,} records")

# Two-part entries
print(f"\nTop two-part slash values:")
two_part = has_slash[has_slash.astype(str).str.count('/') == 1]
for v, c in two_part.value_counts().head(15).items():
    print(f"  {c:5,}  [{v}]")

# Triple entries
triple = has_slash[has_slash.astype(str).str.count('/') >= 2]
print(f"\nAll triple-slash values ({len(triple):,} records):")
for v, c in triple.value_counts().items():
    print(f"  {c:5,}  [{v}]")

Slash-Separated Value Analysis
Total slash entries: 1,599 (3.7% of populated)

Slash count distribution:
  1 slash(es): 1,578 records
  2 slash(es): 21 records

Top two-part slash values:
    124  [30/15]
    101  [20/10]
     71  [25/15]
     55  [50/15]
     54  [35/15]
     50  [125/95]
     46  [30/10]
     43  [75/15]
     39  [25/10]
     38  [50/30]
     36  [40/20]
     30  [40/15]
     29  [150/75]
     27  [75/50]
     27  [30/20]

All triple-slash values (21 records):
      5  [150/30/15]
      3  [100/30/15]
      1  [--/50/25]
      1  [150/100/50]
      1  [--/400/40]
      1  [125/75/35]
      1  [100/40/15]
      1  [30/20/10]
      1  [300/40/15]
      1  [200/30/15]
      1  [100/50/15]
      1  [75/35/10]
      1  [100/30/10]
      1  [77/50/20]
      1  [200/100/75]


In [ ]:
# Test whether slash values follow a consistent ordering pattern
# (first value >= second, consistent with on-cover / off-cover pricing)

two_part = has_slash[has_slash.astype(str).str.count('/') == 1]

def parse_slash_pair(v):
    parts = str(v).replace(',', '').split('/')
    try:
        a = float(parts[0]) if parts[0].strip() != '--' else None
        b = float(parts[1]) if parts[1].strip() != '--' else None
        return a, b
    except:
        return None, None

pairs = two_part.apply(parse_slash_pair)
both_valid = [(a, b) for a, b in pairs if a is not None and b is not None]

first_ge_second = sum(1 for a, b in both_valid if a >= b)
second_gt_first = sum(1 for a, b in both_valid if b > a)
ratios = [round(a / b, 1) for a, b in both_valid if b > 0]

print("Slash Value Ordering Analysis")
print("=" * 60)
print(f"Two-part slash entries with both parts numeric: {len(both_valid):,}")
print(f"  First >= second:  {first_ge_second:,} "
      f"({first_ge_second/len(both_valid)*100:.1f}%)")
print(f"  Second > first:   {second_gt_first:,} "
      f"({second_gt_first/len(both_valid)*100:.1f}%)")
print(f"\nRatio (first / second):")
print(f"  Median: {pd.Series(ratios).median():.1f}x"
      f"   Mean: {pd.Series(ratios).mean():.1f}x")
print(f"\nTop ratio values:")
for v, c in pd.Series(ratios).value_counts().head(10).items():
    print(f"  {v:5.1f}x  {c:5,} records")

print(f"\n--- KEY FINDING ---")
print(f"97% of two-part slash values have first >= second.")
print(f"This is consistent with a fixed-position notation")
print(f"(e.g., tiers of quality - good/better/best) rather than an unordered")
print(f"list of independent valuations.")

Slash Value Ordering Analysis
Two-part slash entries with both parts numeric: 1,535
  First >= second:  1,491 (97.1%)
  Second > first:   44 (2.9%)

Ratio (first / second):
  Median: 2.0x   Mean: 2.8x

Top ratio values:
    2.0x    360 records
    1.7x    157 records
    1.3x    110 records
    1.5x     91 records
    3.0x     87 records
    2.5x     86 records
    5.0x     76 records
    3.3x     70 records
    2.3x     54 records
    1.4x     45 records

--- KEY FINDING ---
97% of two-part slash values have first >= second.
This is consistent with a fixed-position notation
(e.g., on-cover / off-cover) rather than an unordered
list of independent valuations.


---
## 7. Summary & Recommendations

The two-tier architecture established in Section 3 provides the organizing principle for all normalization decisions. Layer 1 fields (parsed text) and Layer 2 fields (`txtTownmark*` classification) require different treatment, and both layers should be preserved.


In [ ]:
# Summary recommendation generator
def generate_normalization_summary(df):
    """
    Generate a summary of normalization recommendations based on the analysis.
    """
    classification_cols = [
        'txtTownmarkShape', 'txtTownmarkLettering', 'txtTownmarkDateFormat',
        'txtTownmarkFraming', 'txtTownmarkColor'
    ]
    
    card = cardinality_analysis(df, classification_cols)
    pop = field_population_report(df)
    
    print("\nSTRONG LOOKUP TABLE CANDIDATES:")
    for _, row in card[card['normalization_candidate'] == True].iterrows():
        print(f"  - {row['column']}: {row['unique_values']} values, "
              f"{row['top_5_concentration_pct']:.0f}% in top 5")
    
    print("\nPRESERVE AS TEXT (high cardinality or sparse):")
    text_candidates = ['txtSizes', 'txtDatesSeen', 'txtColors', 'txtRatesText', 'txtOther']
    for col in text_candidates:
        pop_row = pop[pop['column'] == col]
        if len(pop_row) > 0:
            print(f"  - {col}: {pop_row['unique_values'].values[0]} unique, "
                  f"{pop_row['population_rate'].values[0]:.1f}% populated")
    
    print("\nALWAYS PRESERVE (Layer 1 core):")
    print("  - txtRawStateData (authoritative ASCC source text)")
    print("  - txtPostmark (raw extracted marking text, pre-inheritance)")
    print("  - txtTownPostmark (resolved postmark text, post-inheritance)")
    print("  - txtTown (normalized town name for filtering)")
    print("  - txtColors (parsed color string, device-lifetime scope)")
    print("  - txtRatesText (parsed rate notation from ASCC)")
    
    print("\nSPARSE FIELDS (mostly Layer 2 classification, <30% populated):")
    deprecated = pop[pop['population_rate'] < 30][['column', 'population_rate']]
    for _, row in deprecated.iterrows():
        print(f"  - {row['column']}: {row['population_rate']:.2f}%")

generate_normalization_summary(df)


STRONG LOOKUP TABLE CANDIDATES:
  - txtTownmarkShape: 25 values, 87% in top 5
  - txtTownmarkLettering: 4 values, 100% in top 5
  - txtTownmarkDateFormat: 11 values, 66% in top 5
  - txtTownmarkFraming: 10 values, 92% in top 5

PRESERVE AS TEXT (high cardinality or sparse):
  - txtSizes: 3035 unique, 41.1% populated
  - txtDatesSeen: 9381 unique, 81.0% populated
  - txtColors: 375 unique, 44.9% populated
  - txtRatesText: 3387 unique, 26.6% populated
  - txtOther: 490 unique, 2.2% populated

ALWAYS PRESERVE (Layer 1 core):
  - txtRawStateData (authoritative ASCC source text)
  - txtPostmark (raw extracted marking text, pre-inheritance)
  - txtTownPostmark (resolved postmark text, post-inheritance)
  - txtTown (normalized town name for filtering)
  - txtColors (parsed color string, device-lifetime scope)
  - txtRatesText (parsed rate notation from ASCC)

SPARSE FIELDS (mostly Layer 2 classification, <30% populated):
  - txtRatesText: 26.55%
  - txtDefaultImage: 12.58%
  - txtTownmarkCo